#!/usr/bin/env python3
"""Sync WeRead vocabulary words to Anki via AnkiConnect.

Reads JSON word data (same format as generate_apkg.py), connects to a
running Anki instance via AnkiConnect, compares against existing cards
in the target deck, and adds only *new* words. Existing cards are never
touched, preserving review history and scheduling.

Requires:
    - Anki running with the AnkiConnect plugin installed (code: 2055492159)
    - The "Vocabulary Card (WeRead)" model imported into Anki
      (import the .apkg generated by generate_apkg.py at least once)

Usage:
    python sync_anki.py input.json
    python sync_anki.py input.json --deck "Custom Deck Name"
    python sync_anki.py input.json --dry-run
    python sync_anki.py input.json --no-audio
"""

import argparse
import concurrent.futures
import json
import os
import re
import sys
import tempfile
import time

from ankiconnect import AnkiConnect, AnkiConnectError
from utils import (
    API_DELAY,
    REQUEST_TIMEOUT,
    edge_tts_bytes,
    fetch_word_data,
    lemmatize_word,
    print_progress_bar,
    safe_filename,
)

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

MODEL_NAME = "Vocabulary Card (WeRead)"
WORD_TIMEOUT = 30  # default seconds per word (audio generation)
MAX_CONSECUTIVE_TIMEOUTS = 3

# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Sync WeRead vocabulary to Anki via AnkiConnect"
    )
    parser.add_argument("input_file", help="JSON input file with word entries")
    parser.add_argument(
        "--deck", "-d", required=False, help="Target Anki deck name (auto-derived from JSON if omitted)"
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Show what would be added without actually adding",
    )
    parser.add_argument(
        "--no-audio",
        action="store_true",
        help="Skip audio generation and upload",
    )
    parser.add_argument(
        "--word-timeout",
        type=int,
        default=WORD_TIMEOUT,
        help=f"Max seconds per word for audio generation (default: {WORD_TIMEOUT})",
    )
    parser.add_argument(
        "-v", "--verbose", action="store_true", help="Show detailed progress"
    )
    return parser.parse_args()


# ---------------------------------------------------------------------------
# Utilities (reused from generate_apkg.py patterns)
# ---------------------------------------------------------------------------


# safe_filename(), fetch_word_data() imported from utils
# (fetch_word_data returns (ipa, audio_url, audio_bytes) — we only use ipa and audio_bytes)


# generate_tts_bytes() imported from utils (edge_tts_bytes)


# ---------------------------------------------------------------------------
# Sync logic
# ---------------------------------------------------------------------------


def _process_one_word(
    w: dict,
    book_id: str,
    no_audio: bool,
) -> tuple[dict, list[tuple[str, bytes]], str]:
    """Generate audio and build a note for a single word.

    Runs in a thread so it can be subject to a per-word timeout.

    Returns (note, audio_uploads, ipa).
    """
    word = w["word"]
    lemma = lemmatize_word(word)
    safe = safe_filename(lemma)
    ipa = w.get("ipa", "")
    audio_uploads: list[tuple[str, bytes]] = []

    if not no_audio:
        # Word audio: JSON IPA → SSML (skip API) → Free Dictionary API → Edge TTS fallback
        if ipa:
            tts = edge_tts_bytes(lemma, ipa=ipa)
            if tts:
                audio_uploads.append((f"{safe}_word.mp3", tts))
        else:
            fetched_ipa, _audio_url, api_audio = fetch_word_data(lemma)
            if api_audio:
                audio_uploads.append((f"{safe}_word.mp3", api_audio))
                if fetched_ipa:
                    ipa = fetched_ipa
            else:
                fallback_ipa = fetched_ipa or None
                tts = edge_tts_bytes(lemma, ipa=fallback_ipa)
                if tts:
                    audio_uploads.append((f"{safe}_word.mp3", tts))

        # Sentence audio: Edge TTS on cleaned sentence
        clean = re.sub(r"<[^>]+>", "", w["sentence"])
        sent_tts = edge_tts_bytes(clean)
        if sent_tts:
            audio_uploads.append((f"{safe}_sent.mp3", sent_tts))

    note = build_note_entry(w, ipa, book_id, lemma=lemma)
    return note, audio_uploads, ipa


def build_note_entry(
    word_data: dict,
    ipa: str | None,
    book_id: str,
    lemma: str | None = None,
) -> dict:
    """Build a single AnkiConnect note dict from word data.

    Audio files are referenced as [sound:filename.mp3] — the actual
    media files must be uploaded separately via store_media_file().

    If lemma is provided, it's used for the card Word field, audio filenames,
    and WordId. The original form is only preserved in the sentence.
    """
    display = (lemma or word_data["word"]).strip().lower()
    safe = safe_filename(display)
    word_audio_ref = f"[sound:{safe}_word.mp3]"
    sent_audio_ref = f"[sound:{safe}_sent.mp3]"
    word_id = f"{display}_{book_id}"

    return {
        "deckName": "",  # filled in later by caller
        "modelName": MODEL_NAME,
        "fields": {
            "WordId": word_id,
            "Word": display,
            "Sentence": word_data["sentence"],
            "IPA": ipa or word_data.get("ipa", ""),
            "DefinitionCN": word_data["definition_cn"],
            "TranslationCN": word_data["translation_cn"],
            "WordAudio": word_audio_ref,
            "SentenceAudio": sent_audio_ref,
        },
        "tags": ["weread"],
    }


def sync(
    data: dict,
    deck_name: str,
    dry_run: bool = False,
    no_audio: bool = False,
    verbose: bool = False,
    word_timeout: int = WORD_TIMEOUT,
) -> dict:
    """Run the full sync workflow. Returns a summary dict."""
    words = data["words"]
    book_title = data["book_title"]

    # 1. Connect
    print(f'Connecting to AnkiConnect...')
    ac = AnkiConnect()

    # 2. Ensure deck and model exist
    ac.ensure_deck_and_model(deck_name, MODEL_NAME)
    print(f'  Deck: "{deck_name}"')
    print(f"  Model: {MODEL_NAME}")

    # 3. Get existing WordId map from target deck
    print(f"\nQuerying existing cards in deck...")
    existing = ac.get_word_id_map(deck_name)
    print(f"  Found {len(existing)} existing cards")

    # 4. Identify new words (check lemma-based WordId, fallback to original)
    book_id = data.get("book_id", "")
    new_words = []
    skipped_words = []
    for w in words:
        lemma = lemmatize_word(w["word"])
        original_id = f"{w['word'].strip().lower()}_{book_id}"
        lemma_id = f"{lemma}_{book_id}"
        if lemma_id in existing or original_id in existing:
            skipped_words.append(w)
            if verbose:
                print(f"  SKIP {w['word']} (already in deck)")
        else:
            new_words.append(w)

    print(f"\n  New words to add: {len(new_words)}")
    print(f"  Already in deck: {len(skipped_words)}")

    if not new_words:
        print("\nDeck is up to date — nothing to add.")
        return {
            "added": 0,
            "skipped": len(skipped_words),
            "audio_uploaded": 0,
            "words_added": [],
            "words_skipped": [w["word"] for w in skipped_words],
        }

    if dry_run:
        print(f"\n[DRY RUN] Would add:")
        for w in new_words:
            print(f"  + {w['word']}")
        return {
            "added": len(new_words),
            "skipped": len(skipped_words),
            "audio_uploaded": 0,
            "words_added": [w["word"] for w in new_words],
            "words_skipped": [w["word"] for w in skipped_words],
        }

    # 5. Generate audio and build notes for new words (per-word timeout)
    print(f"\nGenerating audio for {len(new_words)} new words...")
    notes_to_add = []
    audio_uploads: list[tuple[str, bytes]] = []
    timed_out_words: list[str] = []
    consecutive_timeouts = 0

    for i, w in enumerate(new_words, 1):
        word = w["word"]
        lemma = lemmatize_word(word)
        total = len(new_words)
        tag = f" ({lemma})" if lemma != word.lower() else ""
        label = f"{word}{tag}"

        # Run audio generation in a thread with per-word timeout
        with concurrent.futures.ThreadPoolExecutor(max_workers=1) as executor:
            future = executor.submit(_process_one_word, w, book_id, no_audio)
            try:
                note, word_audio, final_ipa = future.result(timeout=word_timeout)
                consecutive_timeouts = 0
                note["deckName"] = deck_name
                notes_to_add.append(note)
                audio_uploads.extend(word_audio)
                if verbose:
                    if not no_audio:
                        has_word = any(fn.endswith("_word.mp3") for fn, _ in word_audio)
                        has_sent = any(fn.endswith("_sent.mp3") for fn, _ in word_audio)
                        audio_status = []
                        if has_word:
                            audio_status.append("word✓")
                        else:
                            audio_status.append("word✗")
                        if has_sent:
                            audio_status.append("sent✓")
                        else:
                            audio_status.append("sent✗")
                        label_v = f"{label}  audio: {', '.join(audio_status)}"
                    else:
                        label_v = f"{label}  audio: skipped"
                    print_progress_bar(i, total, label_v)
                else:
                    print_progress_bar(i, total, label)
            except concurrent.futures.TimeoutError:
                consecutive_timeouts += 1
                timed_out_words.append(word)
                # Start new line before timeout message, then resume bar
                print()
                print(f"  ⏱ TIMEOUT {word} ({consecutive_timeouts}/{MAX_CONSECUTIVE_TIMEOUTS} consecutive)")
                print_progress_bar(i, total, label)
                if consecutive_timeouts >= MAX_CONSECUTIVE_TIMEOUTS:
                    print(f"\n  {MAX_CONSECUTIVE_TIMEOUTS} consecutive timeouts — aborting sync.")
                    for remaining in new_words[i:]:
                        timed_out_words.append(remaining["word"])
                    break

        time.sleep(API_DELAY)

    # Finalize progress bar
    print()

    # 6. Upload media files
    audio_count = 0
    if audio_uploads and not dry_run:
        total_media = len(audio_uploads)
        print(f"\nUploading {total_media} media files...")
        for i_media, (filename, data) in enumerate(audio_uploads, 1):
            try:
                ac.store_media_file(filename, data)
                audio_count += 1
                if verbose:
                    print_progress_bar(i_media, total_media, f"{filename} ({len(data)} bytes)")
                else:
                    print_progress_bar(i_media, total_media)
            except AnkiConnectError as e:
                # New line before error, then resume bar
                print()
                print(f"  ✗ {filename}: {e}")
                print_progress_bar(i_media, total_media)
        # Finalize media progress bar
        print()
        print(f"  Uploaded: {audio_count}/{total_media}")

    # 7. Add notes
    added_count = 0
    duped_count = 0
    if not dry_run and notes_to_add:
        print(f"\nAdding {len(notes_to_add)} new cards to Anki...")
        try:
            result = ac.add_notes(notes_to_add)
            added_count = sum(1 for r in result if r is not None)
            duped_count = sum(1 for r in result if r is None)
            print(f"  Added: {added_count}")
            if duped_count:
                print(f"  Duplicates (not added): {duped_count}")
        except AnkiConnectError as e:
            errmsg = str(e)
            if "duplicate" in errmsg.lower():
                print(f"  All {len(notes_to_add)} already exist (duplicates).")
                duped_count = len(notes_to_add)
            else:
                print(f"Error adding notes: {e}")
                return {
                    "added": 0,
                    "skipped": len(skipped_words),
                    "audio_uploaded": audio_count,
                    "words_added": [],
                    "words_skipped": [w["word"] for w in skipped_words + new_words],
                    "words_timed_out": timed_out_words,
                    "error": errmsg,
                }

    # Summary
    print(f"\n{'='*50}")
    print(f"Sync complete for \"{book_title}\"")
    print(f"  New cards added:  {added_count}")
    print(f"  Already in deck:  {len(skipped_words)}")
    print(f"  Media uploaded:   {audio_count}")
    if timed_out_words:
        print(f"  ⏱ Timed out:      {len(timed_out_words)} word(s)")
        print(f"     ({', '.join(timed_out_words)})")
    print(f"{'='*50}")

    return {
        "added": added_count,
        "skipped": len(skipped_words),
        "audio_uploaded": audio_count,
        "words_added": [w["word"] for w in new_words[:added_count]],
        "words_skipped": [w["word"] for w in skipped_words],
        "words_timed_out": timed_out_words,
    }


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------


def main() -> None:
    args = parse_args()

    # Read input
    with open(args.input_file, "r", encoding="utf-8") as f:
        data = json.load(f)

    # Basic validation
    if not data.get("book_title"):
        print("Error: missing 'book_title' in input", file=sys.stderr)
        sys.exit(1)
    if not data.get("book_id"):
        print("Error: missing 'book_id' in input", file=sys.stderr)
        sys.exit(1)
    if not data.get("words"):
        print("Error: 'words' array is empty", file=sys.stderr)
        sys.exit(1)

    # Deduplicate
    seen = set()
    deduped = []
    for w in data["words"]:
        key = w["word"].strip().lower()
        if key not in seen:
            seen.add(key)
            deduped.append(w)
    if len(deduped) < len(data["words"]):
        print(f"Note: deduplicated {len(data['words']) - len(deduped)} word(s)\n")
    data["words"] = deduped

    # Auto-derive deck name to match generate_apkg.py convention
    if args.deck:
        deck_name = args.deck
    else:
        author = data.get("book_author", "")
        title = data["book_title"]
        deck_name = f"{title} ({author})" if author else f"{title} Vocabulary"

    try:
        result = sync(
            data,
            deck_name,
            dry_run=args.dry_run,
            no_audio=args.no_audio,
            verbose=args.verbose,
            word_timeout=args.word_timeout,
        )
        if result.get("error"):
            sys.exit(1)
    except AnkiConnectError as e:
        print(f"\nError: {e}", file=sys.stderr)
        print(
            "\nMake sure:\n"
            "  1. Anki is running\n"
            '  2. AnkiConnect plugin is installed (add-on code: 2055492159)\n'
            "  3. The Vocabulary Card (WeRead) model exists in Anki\n"
            "     (import an .apkg file from this skill first)",
            file=sys.stderr,
        )
        sys.exit(1)


if __name__ == "__main__":
    main()
