#!/usr/bin/env python3
"""Sync WeRead vocabulary words to Anki via AnkiConnect.

Reads JSON word data (same format as generate_apkg.py), connects to a
running Anki instance via AnkiConnect, compares against existing cards
in the target deck, and adds only *new* words. Existing cards are never
touched, preserving review history and scheduling.

Requires:
    - Anki running with the AnkiConnect plugin installed (code: 2055492159)
    - The "Vocabulary Card (WeRead)" model imported into Anki
      (import the .apkg generated by generate_apkg.py at least once)

Usage:
    python sync_anki.py input.json
    python sync_anki.py input.json --deck "Custom Deck Name"
    python sync_anki.py input.json --dry-run
    python sync_anki.py input.json --no-audio
"""

import argparse
import json
import os
import re
import sys
import tempfile
import time

from ankiconnect import AnkiConnect, AnkiConnectError

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

MODEL_NAME = "Vocabulary Card (WeRead)"
FREE_DICT_API = "https://api.dictionaryapi.dev/api/v2/entries/en"
API_DELAY = 0.35
REQUEST_TIMEOUT = 12

# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Sync WeRead vocabulary to Anki via AnkiConnect"
    )
    parser.add_argument("input_file", help="JSON input file with word entries")
    parser.add_argument(
        "--deck", "-d", required=False, help="Target Anki deck name (auto-derived from JSON if omitted)"
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Show what would be added without actually adding",
    )
    parser.add_argument(
        "--no-audio",
        action="store_true",
        help="Skip audio generation and upload",
    )
    parser.add_argument(
        "-v", "--verbose", action="store_true", help="Show detailed progress"
    )
    return parser.parse_args()


# ---------------------------------------------------------------------------
# Utilities (reused from generate_apkg.py patterns)
# ---------------------------------------------------------------------------


def safe_filename(word: str) -> str:
    safe = re.sub(r"[^a-zA-Z0-9]", "_", word)
    return safe.strip("_").lower() or "word"


# ---------------------------------------------------------------------------
# Audio generation
# ---------------------------------------------------------------------------


def fetch_word_audio(word: str) -> tuple[str | None, bytes | None]:
    """Fetch IPA + word audio from Free Dictionary API.

    Returns (ipa, audio_bytes) — both can be None.
    """
    import requests

    url = f"{FREE_DICT_API}/{word.lower()}"
    try:
        resp = requests.get(url, timeout=REQUEST_TIMEOUT)
        if resp.status_code != 200:
            return None, None
        data = resp.json()
        if not isinstance(data, list) or len(data) == 0:
            return None, None

        entry = data[0]

        # Extract IPA: prefer US, then root, then any
        ipa = None
        phonetics = entry.get("phonetics", [])
        for p in phonetics:
            audio = p.get("audio", "")
            text = p.get("text", "")
            is_us = "us" in audio.lower() or "-us" in str(text).lower()
            if not is_us:
                is_us = any(c in text for c in ("ɚ", "ɑ", "ɝ"))
            if is_us and text:
                ipa = text
                break
        if not ipa:
            ipa = entry.get("phonetic")
        if not ipa:
            for p in phonetics:
                if p.get("text"):
                    ipa = p["text"]
                    break

        # Extract audio (prefer US)
        audio_url = None
        phonetics = entry.get("phonetics", [])
        for p in phonetics:
            if p.get("audio") and (
                "us" in p.get("audio", "").lower()
                or "-us" in str(p.get("text", "")).lower()
            ):
                audio_url = p["audio"]
                break
        if not audio_url:
            for p in phonetics:
                if p.get("audio"):
                    audio_url = p["audio"]
                    break

        audio_bytes = None
        if audio_url:
            try:
                ar = requests.get(audio_url, timeout=REQUEST_TIMEOUT)
                if ar.status_code == 200:
                    audio_bytes = ar.content
            except requests.RequestException:
                pass

        return ipa, audio_bytes

    except requests.RequestException:
        return None, None


def generate_tts_bytes(text: str, lang: str = "en") -> bytes | None:
    """Generate TTS audio for text using gTTS. Returns audio bytes."""
    try:
        from gtts import gTTS

        tts = gTTS(text=text, lang=lang, tld="com", slow=False)
        with tempfile.NamedTemporaryFile(suffix=".mp3", delete=False) as tmp:
            tmp_path = tmp.name
        tts.save(tmp_path)
        with open(tmp_path, "rb") as f:
            data = f.read()
        os.unlink(tmp_path)
        return data
    except Exception:
        return None


# ---------------------------------------------------------------------------
# Sync logic
# ---------------------------------------------------------------------------


def build_note_entry(
    word_data: dict,
    ipa: str | None,
    book_id: str,
) -> dict:
    """Build a single AnkiConnect note dict from word data.

    Audio files are referenced as [sound:filename.mp3] — the actual
    media files must be uploaded separately via store_media_file().
    """
    word = word_data["word"]
    safe = safe_filename(word)
    word_audio_ref = f"[sound:{safe}_word.mp3]"
    sent_audio_ref = f"[sound:{safe}_sent.mp3]"
    word_id = f"{word.strip().lower()}_{book_id}"

    return {
        "deckName": "",  # filled in later by caller
        "modelName": MODEL_NAME,
        "fields": {
            "WordId": word_id,
            "Word": word,
            "Sentence": word_data["sentence"],
            "IPA": ipa or word_data.get("ipa", ""),
            "DefinitionCN": word_data["definition_cn"],
            "TranslationCN": word_data["translation_cn"],
            "WordAudio": word_audio_ref,
            "SentenceAudio": sent_audio_ref,
        },
        "tags": ["weread"],
    }


def sync(
    data: dict,
    deck_name: str,
    dry_run: bool = False,
    no_audio: bool = False,
    verbose: bool = False,
) -> dict:
    """Run the full sync workflow. Returns a summary dict."""
    words = data["words"]
    book_title = data["book_title"]

    # 1. Connect
    print(f'Connecting to AnkiConnect...')
    ac = AnkiConnect()

    # 2. Ensure deck and model exist
    ac.ensure_deck_and_model(deck_name, MODEL_NAME)
    print(f'  Deck: "{deck_name}"')
    print(f"  Model: {MODEL_NAME}")

    # 3. Get existing WordId map from target deck
    print(f"\nQuerying existing cards in deck...")
    existing = ac.get_word_id_map(deck_name)
    print(f"  Found {len(existing)} existing cards")

    # 4. Identify new words (check WordId against existing)
    book_id = data.get("book_id", "")
    new_words = []
    skipped_words = []
    for w in words:
        word_id = f"{w['word'].strip().lower()}_{book_id}"
        if word_id in existing:
            skipped_words.append(w)
            if verbose:
                print(f"  SKIP {w['word']} (already in deck)")
        else:
            new_words.append(w)

    print(f"\n  New words to add: {len(new_words)}")
    print(f"  Already in deck: {len(skipped_words)}")

    if not new_words:
        print("\nDeck is up to date — nothing to add.")
        return {
            "added": 0,
            "skipped": len(skipped_words),
            "audio_uploaded": 0,
            "words_added": [],
            "words_skipped": [w["word"] for w in skipped_words],
        }

    if dry_run:
        print(f"\n[DRY RUN] Would add:")
        for w in new_words:
            print(f"  + {w['word']}")
        return {
            "added": len(new_words),
            "skipped": len(skipped_words),
            "audio_uploaded": 0,
            "words_added": [w["word"] for w in new_words],
            "words_skipped": [w["word"] for w in skipped_words],
        }

    # 5. Generate audio and build notes for new words
    print(f"\nGenerating audio for {len(new_words)} new words...")
    notes_to_add = []
    audio_uploads: list[tuple[str, bytes]] = []

    for i, w in enumerate(new_words, 1):
        word = w["word"]
        safe = safe_filename(word)
        ipa = w.get("ipa", "")

        if verbose:
            print(f"  [{i}/{len(new_words)}] {word}")

        word_audio_bytes = None
        sent_audio_bytes = None

        if not no_audio:
            # Word audio: try Free Dictionary API first, then gTTS
            fetched_ipa, api_audio = fetch_word_audio(word)
            if api_audio:
                word_audio_bytes = api_audio
                if not ipa and fetched_ipa:
                    ipa = fetched_ipa
                if verbose:
                    print(f"    word audio: API ({ipa or 'no IPA'})")
            else:
                tts = generate_tts_bytes(word)
                if tts:
                    word_audio_bytes = tts
                    if verbose:
                        print("    word audio: gTTS fallback")

            if word_audio_bytes:
                audio_uploads.append((f"{safe}_word.mp3", word_audio_bytes))

            # Sentence audio: gTTS
            clean = re.sub(r"<[^>]+>", "", w["sentence"])
            sent_tts = generate_tts_bytes(clean)
            if sent_tts:
                sent_audio_bytes = sent_tts
                audio_uploads.append((f"{safe}_sent.mp3", sent_tts))
                if verbose:
                    print("    sentence audio: gTTS OK")
            else:
                if verbose:
                    print("    sentence audio: gTTS FAILED")

            time.sleep(API_DELAY)
        else:
            if verbose:
                print(f"    audio: skipped (--no-audio)")

        note = build_note_entry(w, ipa, book_id)
        note["deckName"] = deck_name
        notes_to_add.append(note)

    # 6. Upload media files
    audio_count = 0
    if audio_uploads and not dry_run:
        print(f"\nUploading {len(audio_uploads)} media files...")
        for filename, data in audio_uploads:
            try:
                ac.store_media_file(filename, data)
                audio_count += 1
                if verbose:
                    print(f"  ✓ {filename} ({len(data)} bytes)")
            except AnkiConnectError as e:
                print(f"  ✗ {filename}: {e}")
        print(f"  Uploaded: {audio_count}/{len(audio_uploads)}")

    # 7. Add notes
    added_count = 0
    duped_count = 0
    if not dry_run and notes_to_add:
        print(f"\nAdding {len(notes_to_add)} new cards to Anki...")
        try:
            result = ac.add_notes(notes_to_add)
            added_count = sum(1 for r in result if r is not None)
            duped_count = sum(1 for r in result if r is None)
            print(f"  Added: {added_count}")
            if duped_count:
                print(f"  Duplicates (not added): {duped_count}")
        except AnkiConnectError as e:
            errmsg = str(e)
            if "duplicate" in errmsg.lower():
                print(f"  All {len(notes_to_add)} already exist (duplicates).")
                duped_count = len(notes_to_add)
            else:
                print(f"Error adding notes: {e}")
                return {
                    "added": 0,
                    "skipped": len(skipped_words),
                    "audio_uploaded": audio_count,
                    "words_added": [],
                    "words_skipped": [w["word"] for w in skipped_words + new_words],
                    "error": errmsg,
                }

    # Summary
    print(f"\n{'='*50}")
    print(f"Sync complete for \"{book_title}\"")
    print(f"  New cards added:  {added_count}")
    print(f"  Already in deck:  {len(skipped_words)}")
    print(f"  Media uploaded:   {audio_count}")
    print(f"{'='*50}")

    return {
        "added": added_count,
        "skipped": len(skipped_words),
        "audio_uploaded": audio_count,
        "words_added": [w["word"] for w in new_words[:added_count]],
        "words_skipped": [w["word"] for w in skipped_words],
    }


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------


def main() -> None:
    args = parse_args()

    # Read input
    with open(args.input_file, "r", encoding="utf-8") as f:
        data = json.load(f)

    # Basic validation
    if not data.get("book_title"):
        print("Error: missing 'book_title' in input", file=sys.stderr)
        sys.exit(1)
    if not data.get("book_id"):
        print("Error: missing 'book_id' in input", file=sys.stderr)
        sys.exit(1)
    if not data.get("words"):
        print("Error: 'words' array is empty", file=sys.stderr)
        sys.exit(1)

    # Deduplicate
    seen = set()
    deduped = []
    for w in data["words"]:
        key = w["word"].strip().lower()
        if key not in seen:
            seen.add(key)
            deduped.append(w)
    if len(deduped) < len(data["words"]):
        print(f"Note: deduplicated {len(data['words']) - len(deduped)} word(s)\n")
    data["words"] = deduped

    # Auto-derive deck name to match generate_apkg.py convention
    if args.deck:
        deck_name = args.deck
    else:
        author = data.get("book_author", "")
        title = data["book_title"]
        deck_name = f"{title} ({author})" if author else f"{title} Vocabulary"

    try:
        result = sync(
            data,
            deck_name,
            dry_run=args.dry_run,
            no_audio=args.no_audio,
            verbose=args.verbose,
        )
        if result.get("error"):
            sys.exit(1)
    except AnkiConnectError as e:
        print(f"\nError: {e}", file=sys.stderr)
        print(
            "\nMake sure:\n"
            "  1. Anki is running\n"
            '  2. AnkiConnect plugin is installed (add-on code: 2055492159)\n'
            "  3. The Vocabulary Card (WeRead) model exists in Anki\n"
            "     (import an .apkg file from this skill first)",
            file=sys.stderr,
        )
        sys.exit(1)


if __name__ == "__main__":
    main()
