#!/usr/bin/env python3
"""Sync WeRead vocabulary words to Anki via AnkiConnect.

Reads JSON word data (same format as generate_apkg.py), connects to a
running Anki instance via AnkiConnect, compares against existing cards
in the target deck, and adds only *new* words. Existing cards are never
touched, preserving review history and scheduling.

Requires:
    - Anki running with the AnkiConnect plugin installed (code: 2055492159)
    - The "Vocabulary Card (WeRead)" model imported into Anki
      (import the .apkg generated by generate_apkg.py at least once)

Usage:
    python sync_anki.py input.json
    python sync_anki.py input.json --deck "Custom Deck Name"
    python sync_anki.py input.json --dry-run
    python sync_anki.py input.json --no-audio
"""

import argparse
import concurrent.futures
import glob
import json
import os
import platform
import re
import sys
import tempfile
import time

from ankiconnect import AnkiConnect, AnkiConnectError
from utils import (
    edge_tts_bytes,
    lemmatize_word,
    print_progress,
    safe_filename,
)

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

MODEL_NAME = "Vocabulary Card (WeRead)"
WORD_TIMEOUT = 30  # default seconds per word (audio generation)
# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Sync WeRead vocabulary to Anki via AnkiConnect"
    )
    parser.add_argument("input_file", help="JSON input file with word entries")
    parser.add_argument(
        "--deck", "-d", required=False, help="Target Anki deck name (auto-derived from JSON if omitted)"
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Show what would be added without actually adding",
    )
    parser.add_argument(
        "--no-audio",
        action="store_true",
        help="Skip audio generation and upload",
    )
    parser.add_argument(
        "--word-timeout",
        type=int,
        default=WORD_TIMEOUT,
        help=f"Deprecated. API calls have built-in timeouts. (default: {WORD_TIMEOUT})",
    )
    parser.add_argument(
        "--prefetch",
        action="store_true",
        help="Generate audio concurrently and save to temp dir with manifest (no Anki interaction)",
    )
    parser.add_argument(
        "--audio-dir",
        required=False,
        help="Use pre-generated audio from directory (skips audio generation)",
    )
    parser.add_argument(
        "--no-direct-media",
        action="store_true",
        help="Always upload media via AnkiConnect API instead of direct filesystem copy",
    )
    parser.add_argument(
        "--no-ankiweb-sync",
        action="store_true",
        help="Skip triggering AnkiWeb sync after cards are added",
    )
    parser.add_argument(
        "--max-bands",
        type=int,
        default=5,
        help="Maximum number of COCA frequency sub-decks (default: 5)",
    )
    parser.add_argument(
        "--min-band-size",
        type=int,
        default=100,
        help="Minimum words per frequency band (default: 100)",
    )
    parser.add_argument(
        "-v", "--verbose", action="store_true", help="Show detailed progress"
    )
    return parser.parse_args()


# ---------------------------------------------------------------------------
# Utilities (reused from generate_apkg.py patterns)
# ---------------------------------------------------------------------------


# safe_filename(), edge_tts_bytes() imported from utils


# ---------------------------------------------------------------------------
# Sync logic
# ---------------------------------------------------------------------------


def compute_bands(
    level_counts: dict[int, int],
    max_bands: int = 5,
    min_band_size: int = 100,
) -> list[tuple[str, int, int]] | None:
    """Group COCA levels into balanced bands based on actual word counts.

    Greedy partition: walk levels in ascending order, cut when accumulated
    count reaches target (= total / K).  Post-process: merge undersized
    tail band into previous band.

    Returns list of (band_name, lo, hi) or None if no banding needed.
    """
    if not level_counts:
        return None

    total = sum(level_counts.values())
    if total < min_band_size:
        return None

    sorted_levels = sorted(level_counts.keys())
    if len(sorted_levels) <= 1:
        return None

    # Determine number of bands K
    k = min(max_bands, len(sorted_levels), total // min_band_size)
    if k <= 1:
        return None

    target = total / k

    # Greedy partition: cut when running sum >= target, or at natural
    # gaps between non-consecutive levels (gap > 1).
    # Don't cut at gaps if current_sum < min_band_size — avoids creating
    # tiny fragments from the gap detection.
    bands: list[tuple[int, int, int]] = []  # (lo, hi, count)
    current_lo = sorted_levels[0]
    current_sum = 0
    prev_level = current_lo

    for level in sorted_levels:
        count = level_counts[level]
        # Natural gap: start a new band if there's a gap AND current
        # accumulated count is already at least min_band_size
        gap_cut = (level - prev_level > 1 and current_sum >= min_band_size)
        # Target cut: accumulated count reached target
        target_cut = (current_sum > 0 and current_sum >= target
                      and len(bands) < k - 1)
        if gap_cut or target_cut:
            bands.append((current_lo, prev_level, current_sum))
            current_lo = level
            current_sum = 0
        current_sum += count
        prev_level = level

    # Final band
    bands.append((current_lo, sorted_levels[-1], current_sum))

    if len(bands) <= 1:
        return None

    # Post-process: merge undersized bands into smaller neighbor.
    # Repeat until all bands >= min_band_size or only one remains.
    changed = True
    while changed and len(bands) >= 2:
        changed = False
        for i in range(len(bands)):
            _lo, _hi, cnt = bands[i]
            if cnt < min_band_size and len(bands) >= 2:
                if i == 0:
                    # First band: merge into next
                    bands[1] = (bands[i][0], bands[1][2],
                                cnt + bands[1][2])
                    bands.pop(i)
                elif i == len(bands) - 1:
                    # Last band: merge into previous
                    bands[i - 1] = (bands[i - 1][0], bands[i][2],
                                    bands[i - 1][2] + cnt)
                    bands.pop(i)
                else:
                    # Middle band: merge into smaller neighbor
                    if bands[i - 1][2] <= bands[i + 1][2]:
                        bands[i - 1] = (bands[i - 1][0], bands[i][2],
                                        bands[i - 1][2] + cnt)
                    else:
                        bands[i + 1] = (bands[i][0], bands[i + 1][2],
                                        cnt + bands[i + 1][2])
                    bands.pop(i)
                changed = True
                break  # Restart scan after mutation

    if len(bands) <= 1:
        return None

    # Format names
    result: list[tuple[str, int, int]] = []
    for lo, hi, _count in bands:
        if lo == hi:
            result.append((f"COCA {lo}", lo, hi))
        else:
            result.append((f"COCA {lo}-{hi}", lo, hi))

    return result


def _count_coca_levels(words: list[dict]) -> dict[int, int]:
    """Count words per COCA level from the words array."""
    level_counts: dict[int, int] = {}
    for w in words:
        lvl = w.get("coca_level")
        if isinstance(lvl, int) and 1 <= lvl <= 25:
            level_counts[lvl] = level_counts.get(lvl, 0) + 1
    return level_counts


def _get_existing_across_decks(
    ac: "AnkiConnect",  # noqa: F821
    parent_deck: str,
    bands: list[tuple[str, int, int]],
) -> dict[str, int]:
    """Query existing WordId→note_id across parent deck and all sub-decks."""
    all_decks = [parent_deck] + [f"{parent_deck}::{name}" for name, _lo, _hi in bands]
    existing: dict[str, int] = {}
    for deck in all_decks:
        existing.update(ac.get_word_id_map(deck))
    return existing


# Words lemminflect can't distinguish as derivational adjectives.
_SPACY_NLP = None   # cached spaCy model
_CMUDICT: dict[str, list[list[str]]] | None = None  # cached cmudict


def _load_cmudict() -> dict[str, list[list[str]]]:
    """Load CMU Pronouncing Dictionary (cached)."""
    global _CMUDICT
    if _CMUDICT is not None:
        return _CMUDICT
    _CMUDICT = {}
    try:
        from pathlib import Path
        path = (
            Path(__file__).resolve().parent.parent
            / "lib" / "data" / "cmudict.dict"
        )
        if not path.exists():
            return _CMUDICT
        with open(path, encoding="utf-8", errors="replace") as fh:
            for line in fh:
                line = line.strip()
                if not line or line.startswith(";;;"):
                    continue
                parts = line.split()
                word = parts[0].lower().rstrip(")").split("(")[0]
                phones = parts[1:]
                if word not in _CMUDICT:
                    _CMUDICT[word] = []
                _CMUDICT[word].append(phones)
    except Exception:
        pass
    return _CMUDICT


# ARPAbet → IPA phoneme map
_ARPABET_TO_IPA = {
    "AA": "ɑː", "AE": "æ",  "AH": "ʌ",  "AO": "ɔː", "AW": "aʊ",
    "AY": "aɪ", "EH": "e",  "ER": "ɜːr","EY": "eɪ", "IH": "ɪ",
    "IY": "iː", "OW": "oʊ", "OY": "ɔɪ", "UH": "ʊ",  "UW": "uː",
    "B": "b",   "CH": "tʃ", "D": "d",   "DH": "ð",  "F": "f",
    "G": "ɡ",   "HH": "h",  "JH": "dʒ","K": "k",   "L": "l",
    "M": "m",   "N": "n",   "NG": "ŋ",  "P": "p",   "R": "r",
    "S": "s",   "SH": "ʃ",  "T": "t",   "TH": "θ",  "V": "v",
    "W": "w",   "Y": "j",   "Z": "z",   "ZH": "ʒ",
}


def _pick_best_pronunciation(
    entries: list[list[str]], claude_ipa: str
) -> list[str]:
    """Pick the cmudict entry closest to Claude's IPA by vowel match."""
    # Extract vowel set from Claude IPA (simplified)
    claude_vowels = set()
    for ch in claude_ipa.strip("/"):
        if ch in "iɪeæɑɔoʊuʌəɜa":
            claude_vowels.add(ch)

    def score(phones: list[str]) -> int:
        s = 0
        for p in phones:
            base = p.rstrip("012")
            mapped = _ARPABET_TO_IPA.get(base, "")
            # Count matching vowels (approximate)
            for ch in mapped:
                if ch in claude_vowels:
                    s += 1
            # Prefer exact stress match
            if p[-1].isdigit() and "ˈ" in claude_ipa and p.endswith("1"):
                s += 1
        return s

    best = max(entries, key=score)
    return best


def _cmu_ipa(word: str, claude_ipa: str = "") -> str | None:
    """Look up IPA for *word* in cmudict.  Returns None if not found.

    For multi-pronunciation words, *claude_ipa* is used as a tiebreaker
    to pick the phonetically closest entry (handles heteronyms like
    read/read, wound/wound).  Without a Claude IPA, defaults to the
    first entry.
    """
    cmu = _load_cmudict()
    w = word.lower()
    if w not in cmu:
        return None
    # Single pronunciation → use directly
    entries = cmu[w]
    if len(entries) == 1 or not claude_ipa:
        phones = entries[0]
    else:
        # Multiple → pick closest to Claude's IPA by vowel match
        phones = _pick_best_pronunciation(entries, claude_ipa)
    # Convert ARPAbet phones to IPA string
    vowel_count = sum(1 for p in phones if any(c.isdigit() for c in p))
    result: list[str] = []
    for p in phones:
        stress = ""
        if p[-1].isdigit():
            if p[-1] == "1" and vowel_count > 1:
                stress = "ˈ"
            elif p[-1] == "2" and vowel_count > 1:
                stress = "ˌ"
            p = p[:-1]
        ipa = _ARPABET_TO_IPA.get(p, p.lower())
        if stress:
            result.append(stress)
        result.append(ipa)
    return "/" + "".join(result) + "/"


def _get_spacy():
    """Load spaCy model (cached)."""
    global _SPACY_NLP
    if _SPACY_NLP is None:
        try:
            import spacy
            _SPACY_NLP = spacy.load("en_core_web_sm")
        except Exception:
            pass
    return _SPACY_NLP


def resolve_lemma(word: str, json_lemma: str) -> str:
    """Resolve the canonical lemma for a word.

    Strategy (in priority order):

    1. Explicit override: *json_lemma* differs from the surface form
       → Claude set it deliberately (e.g. derivational adj).  Trust it.

    2. Auto-correct: *json_lemma* is empty or equals the surface form
       AND the word is not a derivational adjective → run
       lemmatize_word().

    3. IRREG fallback for cases lemmatize_word() misses.

    4. Otherwise keep the provided lemma (or surface form).

    Claude should only set *lemma* for derivational adjectives /
    deliberate overrides.  Regular inflectional forms should have an
    empty *lemma* — lemmatize_word() handles those automatically.
    """
    w = word.lower()
    jl = json_lemma.strip().lower() if json_lemma else ""

    # 1. Explicit override: Claude set lemma → trust it unconditionally.
    #    The quality checklist ensures Claude sets it correctly for
    #    derivational adjectives (blundering, accomplished, etc.).
    if jl:
        return jl

    # 2. Regular -est/-er/-ier/-iest patterns (before lemmatize_word,
    #    which may over-reduce: lemminflect maps *happier* → *hap*).
    #    Only apply when the word is NOT already in COCA, preventing
    #    false reductions like beer→bee, anger→ange, sacred→sacre.
    _coca: set[str] = set()
    try:
        from lib.coca import load_coca
        _coca = load_coca()
    except ImportError:
        pass
    # -est/-iest suffixes are reliable (superlatives, near-zero false
    # positives).  -er/-ier can match nouns (beer, anger, fiber) so we
    # only apply those when the word is NOT already in COCA.
    if w not in _coca or w.endswith("est") or w.endswith("iest") or w.endswith("ier"):
        for sfx, slen in [("iest", 4), ("est", 3), ("ier", 3), ("er", 2)]:
            if w.endswith(sfx) and len(w) > slen + 1:
                stem = w[:-slen]
                if sfx.startswith("i"):
                    cand = stem + "y"          # happiest→happy, happier→happy
                else:
                    cand = stem                 # smallest→small, closer→close?
                    # Doubled consonant: biggest→big (only when the stem ends
                    # in CVC where C is the doubled consonant & not a true
                    # double-letter ending like -ll, -ss, -ff in the base).
                    if len(stem) >= 3 and stem[-1] == stem[-2] and stem[-1] not in "aeiouyls":
                        cand2 = stem[:-1]
                        cand = cand2
                    # Dropped-e: closest→close (only if stem doesn't already
                    # look like a valid word, e.g. *small* from *smallest*).
                    if cand == stem and not (
                        len(stem) >= 2
                        and stem[-1] == stem[-2]
                        and stem[-1] not in "aeiouy"
                    ):
                        cand_e = stem + "e"
                        if cand_e in _coca and cand_e != w:
                            cand = cand_e
                if cand != w and len(cand) < len(w):
                    return cand
                break

    # 3. Auto-correct inflectional forms.
    #    Apply COCA gate: only reduce if the word is NOT already in COCA,
    #    OR the reduced form is also a valid COCA entry.  This prevents
    #    false reductions like sacred→sacre where lemminflect hallucinates.
    #    (spaCy safety net in _process_one_word catches any remaining
    #    derivational adjective mis-reductions.)
    #    Note: step 3 no longer returns early — it sets *reduced* and
    #    falls through to Nation validation at step 5.
    reduced = lemmatize_word(word)
    if reduced != w and (w not in _coca or reduced in _coca):
        pass  # keep reduced, fall through to validation
    else:
        reduced = w  # reset: no valid reduction found

    # 4. lemmatize_word couldn't reduce — try lemminflect with COCA gating.
    #    Instead of returning directly, update *reduced* and fall through
    #    to the Nation validation at step 5.
    try:
        from lemminflect import getLemma

        for upos in ("VERB", "NOUN"):
            lemmas = getLemma(w, upos)
            if lemmas:
                for lemma in lemmas:
                    cand = lemma.lower()
                    if cand == w:
                        continue
                    # Path 1: word NOT in COCA → reduce if lemma IS in COCA
                    if w not in _coca and cand in _coca:
                        reduced = cand
                        break
                    # Path 2: both in COCA — accept the reduction.
                    # For VERB: accept regardless of length (had→have is
                    # longer); Nation validation at step 5 catches
                    # cross-family false positives (abode n.→abide v.).
                    # For NOUN: require shorter lemma (cats→cat safe;
                    # same-length risks: abode→abide, ran→run).
                    if w in _coca and cand in _coca:
                        if upos == "VERB" or len(cand) < len(w):
                            reduced = cand
                            break
                if reduced != w:
                    break
    except ImportError:
        pass

    # 5. Nation word family cross-validation:
    #    If the reduced lemma belongs to a DIFFERENT word family than
    #    the original word, it's a cross-family misreduction
    #    (e.g. twined→twin, but Nation says twined belongs to twine).
    #    Note: this does NOT catch intra-family reductions like
    #    blundering→blunder — Claude override + spaCy POS gate
    #    handle those.
    #    If the reduced lemma belongs to a DIFFERENT word family than
    #    the original word, it's a cross-family misreduction
    #    (e.g. twined→twin, but Nation says twined belongs to twine).
    #    Note: this does NOT catch intra-family reductions like
    #    blundering→blunder — Claude override + spaCy POS gate
    #    handle those.
    if reduced != w:
        try:
            from lib.coca import get_word_headword
            nation_head = get_word_headword(w)
            if nation_head:
                lemma_head = get_word_headword(reduced)
                if lemma_head and nation_head != lemma_head:
                    print(f"  [WARN] [{word}] lemmatize→{reduced} "
                          f"(Nation: {lemma_head} family) but Nation says "
                          f"'{w}' → {nation_head} family. "
                          f"Keeping original form.",
                          file=sys.stderr)
                    return w
        except ImportError:
            pass

    # Fall through: return reduced form (if valid), or keep original
    if reduced != w:
        return reduced
    return jl or w


def _has_be_to_pattern(doc, vbn_idx: int) -> bool:
    """Check if the VBN at vbn_idx is part of a "be VBN to <verb>" pattern.

    "be astonished to see", "be surprised to hear" etc. — emotional
    adjectives with to-infinitive complement.  spaCy's small model often
    tags these as VERB/VBN rather than ADJ, but the structural pattern
    (form of "be" before, "to" + verb after) is a reliable adjective signal.
    """
    # Check preceding tokens: a form of "be" within 3 tokens before
    be_forms = {"am", "is", "are", "was", "were", "be", "been", "being"}
    has_be = False
    for i in range(max(0, vbn_idx - 3), vbn_idx):
        if doc[i].text.lower() in be_forms:
            has_be = True
            break
    if not has_be:
        return False

    # Check following tokens: "to" within 2 tokens after, followed by verb
    for i in range(vbn_idx + 1, min(vbn_idx + 3, len(doc))):
        if doc[i].text.lower() == "to" and i + 1 < len(doc):
            if doc[i + 1].pos_ == "VERB":
                return True
            # Also catch adverbs between "to" and verb: "to properly see"
            if i + 2 < len(doc) and doc[i + 2].pos_ == "VERB":
                return True
    return False


def _process_one_word(
    w: dict,
    book_id: str,
    no_audio: bool,
) -> tuple[dict, list[tuple[str, bytes]], str]:
    """Generate audio and build a note for a single word.

    Runs in a thread so it can be subject to a per-word timeout.

    Returns (note, audio_uploads, ipa).
    """
    word = w["word"]
    json_lemma = w.get("lemma", "").strip()
    lemma = resolve_lemma(word, json_lemma)

    # Safety net: for -ed/-ing words that resolve_lemma reduced away from
    # the surface form, verify with spaCy's sentence-context parse.
    #
    # Three signals that the surface form is a derivational adjective
    # (keep it) rather than a verb inflection (reduce to stem):
    #
    #   1. Dependency-based: the word has an adjectival grammatical function
    #      (acomp/oprd/attr/amod).  This encodes "be/seem + adjective"
    #      structurally and is more reliable than POS tags alone.
    #      — catches: surprised (acomp), disappointed (oprd), distinguished (amod)
    #
    #   2. Lemma-based: spaCy returns the surface form as its own lemma
    #      (belt & suspenders for signal 1; also catches conj like embarrassed).
    #      — catches: embarrassed (conj, but lemma=embarrassed)
    #
    #   3. be-to pattern: "be VBN to <verb>" — syntactic hallmark of emotional
    #      adjectives.  Needed because spaCy sometimes misparses this as ROOT
    #      (passive) instead of acomp, e.g. "be astonished to see".
    #      — catches: astonished (ROOT, but be-to pattern matches)
    wl = word.lower()
    if lemma != wl and wl.endswith(("ed", "ing")):
        sent = w.get("sentence", "")
        if sent:
            nlp = _get_spacy()
            if nlp is not None:
                try:
                    doc = nlp(sent)
                    for token in doc:
                        if token.text.lower() == wl:
                            # Signal 1: adjectival dependency relation
                            if token.dep_ in ("acomp", "oprd", "attr", "amod"):
                                lemma = wl
                                break
                            # Signal 2: spaCy lemma == surface form
                            if token.lemma_.lower() == wl:
                                lemma = wl
                                break
                            # Signal 3: be VBN to <verb> structural pattern
                            if token.tag_ == "VBN" and _has_be_to_pattern(doc, token.i):
                                lemma = wl
                                break
                except Exception:
                    pass

    safe = safe_filename(lemma)

    # IPA: cmudict preferred.  Claude's IPA used as tiebreaker for
    # heteronyms (read/read, wound/wound) and fallback for OOV words.
    cmu_ipa = _cmu_ipa(lemma, w.get("ipa", ""))
    ipa = cmu_ipa if cmu_ipa else w.get("ipa", "")

    audio_uploads: list[tuple[str, bytes]] = []

    if not no_audio:
        # Word audio: Edge TTS on lemma (with IPA if available).
        #   Include book_id — heteronyms like "wound" have different
        #   pronunciations in different books.
        if ipa:
            tts = edge_tts_bytes(lemma, ipa=ipa)
            if tts:
                audio_uploads.append((f"{safe}_{book_id}_word.mp3", tts))

        # Sentence audio: Edge TTS on cleaned sentence.
        #   Include book_id in filename — different books have different
        #   sentences for the same lemma (e.g. "beautiful" in two books).
        clean = re.sub(r"<[^>]+>", "", w["sentence"])
        sent_tts = edge_tts_bytes(clean)
        if sent_tts:
            audio_uploads.append((f"{safe}_{book_id}_sent.mp3", sent_tts))

    note = build_note_entry(w, ipa, book_id, lemma=lemma)
    return note, audio_uploads, ipa


def build_note_entry(
    word_data: dict,
    ipa: str | None,
    book_id: str,
    lemma: str | None = None,
) -> dict:
    """Build a single AnkiConnect note dict from word data.

    Audio files are referenced as [sound:filename.mp3] — the actual
    media files must be uploaded separately via store_media_file().

    If lemma is provided, it's used for the card Word field, audio filenames,
    and WordId. The original form is only preserved in the sentence.
    """
    display = (lemma or word_data["word"]).strip().lower()
    safe = safe_filename(display)
    word_audio_ref = f"[sound:{safe}_{book_id}_word.mp3]"
    sent_audio_ref = f"[sound:{safe}_{book_id}_sent.mp3]"
    word_id = f"{display}_{book_id}"

    return {
        "deckName": "",  # filled in later by caller
        "modelName": MODEL_NAME,
        "fields": {
            "WordId": word_id,
            "Word": display,
            "Sentence": word_data["sentence"],
            "IPA": ipa or word_data.get("ipa", ""),
            "DefinitionCN": word_data["definition_cn"],
            "TranslationCN": word_data["translation_cn"],
            "WordAudio": word_audio_ref,
            "SentenceAudio": sent_audio_ref,
        },
        "tags": ["weread"],
    }


def _validate_word_entries(words: list[dict]) -> list[str]:
    """Validate word entries before sync. Returns list of error messages (empty = pass).

    Checks sentence length (≤150 chars), <b> tag matches word field,
    word actually appears in sentence text (after stripping tags),
    and required fields (ipa, definition_cn, translation_cn) are non-empty.

    Soft warnings (IPA format, definition sanity) are printed to stderr
    directly and do NOT block sync.
    """
    errors = []
    for w in words:
        word = w.get("word", "")
        sentence = w.get("sentence", "")

        # 1. <b> content must match word field (hard error)
        b_match = re.search(r"<b>(.*?)</b>", sentence)
        b_text = b_match.group(1) if b_match else ""
        if b_text != word:
            errors.append(f"[{word}] <b> mismatch: <b>{b_text}</b> ≠ word '{word}'")

        # 1b. <b> must wrap the COMPLETE surface word — detect tag-split
        #     errors like <b>dip</b>ped, <b>nail</b>s, <b>bind</b>ing
        if b_match and b_text:
            after = sentence[b_match.end():]
            if after and after[0].isalpha() and after[0].islower():
                remaining = ""
                for ch in after:
                    if ch.isalpha():
                        remaining += ch
                    else:
                        break
                full_word = b_text + remaining
                errors.append(
                    f"[{word}] <b> tag splits surface word: "
                    f"<b>{b_text}</b>{remaining} → should wrap complete "
                    f"surface form '<b>{full_word}</b>'"
                )

        # 2. Sentence must contain the word (case-insensitive, after stripping tags) — hard error
        clean_sentence = re.sub(r"<[^>]+>", "", sentence)
        if word.lower() not in clean_sentence.lower():
            errors.append(
                f"[{word}] word not found in sentence: "
                f"'{word}' not in '{clean_sentence[:80]}{'...' if len(clean_sentence) > 80 else ''}'"
            )

        # 3. Sentence length ≤ 150 chars (hard error)
        if len(sentence) > 150:
            errors.append(f"[{word}] sentence too long: {len(sentence)} chars (max 150)")

        # 4. Required fields non-empty (hard error)
        for field in ["ipa", "definition_cn", "translation_cn"]:
            if not w.get(field):
                errors.append(f"[{word}] missing '{field}'")

        # 4.5 lemma sanity: if explicitly set AND differs from both the
        #     surface word AND lemmatize_word(word) → suspicious.
        #     False positives: same-length irregulars (dig→dug, wear→wore)
        #     where lemmatize_word can't reduce due to the length gate.
        #     These are valid overrides that go TO a shorter-or-equal form.
        #     True positives (beautiful→beautifully) go TO a longer form.
        json_lemma = w.get("lemma", "").strip()
        if json_lemma:
            resolved = resolve_lemma(word, "")
            machine = lemmatize_word(word)
            if (json_lemma.lower() != word.lower()
                    and json_lemma.lower() != machine.lower()
                    and len(json_lemma) > len(word)):  # longer = true error
                errors.append(
                    f"[{word}] suspicious lemma '{json_lemma}': differs from both "
                    f"surface form '{word}' and lemmatize_word() result '{machine}'. "
                    f"Leave lemma empty for regular inflection (auto-correct → '{resolved}')"
                )

        # --- Soft warnings (stderr only, do not block sync) ---

        # 5. IPA format sanity check
        ipa = w.get("ipa", "")

        # 6. IPA matches lemma (not surface form): e.g. lemma=hunt
        #    but IPA=/ˈhʌntɪŋ/ (for hunting).
        json_lemma2 = w.get("lemma", "").strip()
        resolved = resolve_lemma(word, json_lemma2)
        if ipa and resolved != word.lower() and "/ɪŋ/" in ipa and not resolved.endswith("ing"):
            print(
                f"  [WARN] [{word}] IPA contains /ɪŋ/ but lemma '{resolved}' "
                f"does not end in -ing (surface form: '{word}')",
                file=sys.stderr,
            )
        if ipa:
            ipa_clean = ipa.strip()
            if "/" not in ipa_clean:
                print(f"  [WARN] [{word}] IPA missing '/' delimiters: {ipa}", file=sys.stderr)
            else:
                # Strip delimiters and stress marks, count phoneme chars
                phonemes = re.sub(r"[/ˈˌ.]", "", ipa_clean)
                if len(phonemes) < 2:
                    print(f"  [WARN] [{word}] IPA too short: {ipa}", file=sys.stderr)
            if re.search(r"[一-鿿]", ipa_clean):
                print(f"  [WARN] [{word}] IPA contains Chinese characters: {ipa}", file=sys.stderr)

        # 6. Definition sanity check
        definition = w.get("definition_cn", "")
        if definition:
            cjk_count = len(re.findall(r"[一-鿿]", definition))
            if cjk_count < 2:
                print(f"  [WARN] [{word}] definition_cn has <2 Chinese chars: '{definition}'", file=sys.stderr)
            if definition.strip().lower() == word.lower():
                print(f"  [WARN] [{word}] definition_cn equals word: '{definition}'", file=sys.stderr)

        # 7. Sentence fragment detection (soft warnings, do not block sync)
        clean = re.sub(r"<[^>]+>", "", sentence).strip()
        if clean:
            # 7a. Starts with lowercase letter — suggests mid-sentence extraction
            first_char = clean[0]
            if first_char.isalpha() and first_char.islower():
                print(
                    f"  [WARN] [{word}] sentence starts with lowercase "
                    f"'{first_char}' — may be a truncated fragment",
                    file=sys.stderr,
                )

            # 7b. No finite verb detected — suggests noun phrase fragment
            has_finite_verb = bool(
                re.search(r'\b(?:is|are|was|were|am|has|have|had|do|does|did|'
                          r'will|would|can|could|shall|should|may|might|must)\b',
                          clean, re.IGNORECASE)
            )
            if not has_finite_verb:
                # Check for past tense / 3rd-person verbs: word ending in -ed, -s
                # (excluding common non-verb -s: this, his, us, thus, etc.)
                verb_ending = bool(
                    re.search(r'\b\w+(?:ed|s)\b', clean)
                )
                if not verb_ending:
                    print(
                        f"  [WARN] [{word}] sentence may lack a finite verb "
                        f"— possible noun phrase fragment: '{clean[:80]}{"..." if len(clean) > 80 else ""}'",
                        file=sys.stderr,
                    )

            # 7c. Ends with function word — strong signal of mid-clause truncation.
            #      Prepositions and conjunctions expect a complement; when they are
            #      the last word, the sentence is almost certainly incomplete.
            _FUNCTION_ENDINGS: set[str] = {
                # Prepositions (require an object)
                "from", "with", "at", "for", "to", "of", "in", "on", "by",
                "about", "into", "onto", "upon", "within", "without", "through",
                "across", "along", "around", "before", "after", "between",
                "among", "during", "until", "against", "toward", "towards",
                "over", "under", "behind", "beside", "beneath",
                # Conjunctions (expect a following clause)
                "and", "but", "or", "nor", "so", "yet", "because",
                "although", "though", "while", "when", "where",
                "since", "if", "unless", "until", "as",
                # Auxiliaries (expect a main verb)
                "had", "has", "was", "were", "could", "would", "should",
            }
            last_word = re.split(r'\s+', clean.rstrip('"\'') + ' ')[-2].strip().lower()
            if last_word in _FUNCTION_ENDINGS:
                errors.append(
                    f"[{word}] sentence ends with function word "
                    f"'{last_word}' — likely truncated fragment"
                )

    return errors


def _find_anki_media_dir() -> str | None:
    """Locate Anki's collection.media directory on the local filesystem.

    Probes common OS paths (including WSL2 → Windows host). Returns the
    first writable collection.media directory found, or None.
    """
    candidates: list[str] = []
    home = os.path.expanduser("~")

    if platform.system() == "Windows":
        candidates.append(os.path.join(os.getenv("APPDATA", ""), "Anki2"))
    else:
        # Native Linux
        candidates.append(os.path.join(home, ".local", "share", "Anki2"))
        # Flatpak
        candidates.append(
            os.path.join(home, ".var", "app", "net.ankiweb.Anki", "data", "Anki2")
        )
        # macOS
        candidates.append(
            os.path.join(home, "Library", "Application Support", "Anki2")
        )
        # WSL2 — Anki runs on the Windows host; search /mnt/c/Users/**
        wsl_users = glob.glob("/mnt/c/Users/*/AppData/Roaming/Anki2")
        candidates.extend(wsl_users)

    for base in candidates:
        if not os.path.isdir(base):
            continue
        for profile in os.listdir(base):
            media_dir = os.path.join(base, profile, "collection.media")
            if os.path.isdir(media_dir) and os.access(media_dir, os.W_OK):
                return media_dir
    return None


def _upload_media_direct(
    audio_uploads: list[tuple[str, bytes]], media_dir: str, verbose: bool = False
) -> int:
    """Copy audio files directly into Anki's collection.media directory.

    Much faster than AnkiConnect storeMediaFile (~0.7s for 124 files vs
    ~80s through the API) because it bypasses per-file base64 decode +
    SQLite write inside AnkiConnect.

    Returns the number of files successfully copied.
    """
    total = len(audio_uploads)
    copied = 0
    for i, (filename, data) in enumerate(audio_uploads, 1):
        dest = os.path.join(media_dir, filename)
        try:
            with open(dest, "wb") as f:
                f.write(data)
            copied += 1
            if verbose:
                print_progress(i, total, f"{filename} ({len(data)} bytes)")
            else:
                print_progress(i, total)
        except OSError:
            print()
            print(f"  ✗ {filename}: write failed")
            print_progress(i, total)
    return copied


def _repair_audio(
    ac: AnkiConnect, lemma: str, sentence: str, book_id: str
) -> None:
    """Re-upload word + sentence audio for a repaired card."""
    safe = safe_filename(lemma)
    # Word audio
    word_tts = edge_tts_bytes(lemma)
    if word_tts:
        ac.store_media_file(f"{safe}_{book_id}_word.mp3", word_tts)
    # Sentence audio
    if sentence:
        clean = re.sub(r"<[^>]+>", "", sentence)
        sent_tts = edge_tts_bytes(clean)
        if sent_tts:
            ac.store_media_file(f"{safe}_{book_id}_sent.mp3", sent_tts)


def sync(
    data: dict,
    deck_name: str,
    dry_run: bool = False,
    no_audio: bool = False,
    verbose: bool = False,
    word_timeout: int = WORD_TIMEOUT,
    prefetch: bool = False,
    audio_dir: str | None = None,
    no_direct_media: bool = False,
    no_ankiweb_sync: bool = False,
    max_bands: int = 5,
    min_band_size: int = 100,
) -> dict:
    """Run the full sync workflow. Returns a summary dict."""
    words = data["words"]
    book_title = data["book_title"]

    book_id = data.get("book_id", "")

    # 1. Connect to Anki (skip for prefetch — audio-only mode)
    ac = None

    # Compute frequency bands from the full word list (before dedup).
    # band_assignment maps word_index in new_words → deck_name;
    # populated after new_words is finalized below.
    band_assignment: dict[int, str] = {}
    bands = compute_bands(
        _count_coca_levels(words), max_bands, min_band_size
    )

    if not prefetch:
        print(f'Connecting to AnkiConnect...')
        ac = AnkiConnect()

        # 2. Create hierarchical decks (or flat deck if no bands)
        if bands:
            # Create parent deck first
            ac.ensure_deck_and_model(deck_name, MODEL_NAME)
            print(f'  Deck: "{deck_name}" (parent)')

            # Create each band sub-deck
            for band_name, _lo, _hi in bands:
                sub_deck = f"{deck_name}::{band_name}"
                ac.ensure_deck_and_model(sub_deck, MODEL_NAME)
                print(f'    └ "{band_name}"')

            # Query existing cards across parent and all sub-decks
            print(f"\nQuerying existing cards across all sub-decks...")
            existing = _get_existing_across_decks(ac, deck_name, bands)
            print(f"  Found {len(existing)} existing cards")
        else:
            # Single flat deck
            ac.ensure_deck_and_model(deck_name, MODEL_NAME)
            print(f'  Deck: "{deck_name}"')
            print(f"  Model: {MODEL_NAME}")

            # Get existing WordId map from target deck
            print(f"\nQuerying existing cards in deck...")
            existing = ac.get_word_id_map(deck_name)
            print(f"  Found {len(existing)} existing cards")
    else:
        existing = {}

    # 5. Identify new words (check lemma-based WordId, fallback to original).
    #    Repair cards whose WordId still uses the surface form instead of
    #    the resolved lemma (e.g. crossing_xxx → cross_xxx).
    new_words = []
    skipped_words = []
    repaired = 0
    for w in words:
        json_lemma = w.get("lemma", "").strip()
        lemma = resolve_lemma(w["word"], json_lemma)
        original_id = f"{w['word'].strip().lower()}_{book_id}"
        lemma_id = f"{lemma}_{book_id}"
        if lemma_id in existing or original_id in existing:
            skipped_words.append(w)
            # Repair: if the card exists under the surface-form WordId
            # but the resolved lemma differs, update ALL dependent fields
            # AND re-upload audio under the new filename.
            if ac and original_id in existing and lemma_id != original_id:
                old_nid = existing[original_id]
                safe = safe_filename(lemma)
                fields = {
                    "WordId": lemma_id,
                    "Word": lemma,
                    "WordAudio": f"[sound:{safe}_{book_id}_word.mp3]",
                    "SentenceAudio": f"[sound:{safe}_{book_id}_sent.mp3]",
                }
                # IPA from cmudict if available
                cmu = _cmu_ipa(lemma)
                if cmu:
                    fields["IPA"] = cmu
                ac.update_note_fields(old_nid, fields)

                # Re-upload audio with new filenames (word + sentence)
                _repair_audio(ac, lemma, w.get("sentence", ""), book_id)
                repaired += 1
                if verbose:
                    print(f"  REPAIR {w['word']} → {lemma} (WordId, audio, IPA updated)")
            elif verbose:
                print(f"  SKIP {w['word']} (already in deck)")
        else:
            new_words.append(w)

    if repaired:
        print(f"  Repaired: {repaired} card(s) (surface-form WordId → lemma)")

    # 5b. Detect duplicate WordIds within the batch itself (e.g. fed + feeding
    #     both lemmatize to feed).  Keep the first occurrence, warn about rest.
    seen_ids: set[str] = set()
    deduped_new: list[dict] = []
    intra_dupes = 0
    for w in new_words:
        jl2 = w.get("lemma", "").strip()
        lm = resolve_lemma(w["word"], jl2)
        wid = f"{lm}_{book_id}"
        if wid in seen_ids:
            intra_dupes += 1
            if verbose:
                print(f"  SKIP {w['word']} (duplicate WordId in batch: {wid})")
        else:
            seen_ids.add(wid)
            deduped_new.append(w)
    if intra_dupes:
        print(f"  Intra-batch duplicates removed: {intra_dupes}")
    new_words = deduped_new

    # Populate band_assignment: map each new_word index to its sub-deck
    if bands:
        band_map: dict[tuple[int, int], str] = {}  # (lo, hi) -> sub_deck_name
        for band_name, lo, hi in bands:
            band_map[(lo, hi)] = f"{deck_name}::{band_name}"
        for idx, w in enumerate(new_words):
            lvl = w.get("coca_level")
            if isinstance(lvl, int):
                for (lo, hi), sub_deck in band_map.items():
                    if lo <= lvl <= hi:
                        band_assignment[idx] = sub_deck
                        break
            # Words without a valid coca_level stay in the parent deck
            if idx not in band_assignment:
                band_assignment[idx] = deck_name
        # Print band distribution
        band_counts: dict[str, int] = {}
        for deck in band_assignment.values():
            short = deck.split("::")[-1] if "::" in deck else deck
            band_counts[short] = band_counts.get(short, 0) + 1
        print(f"\n  Band distribution: {', '.join(f'{k}: {v}' for k, v in band_counts.items())}")

    print(f"\n  New words to add: {len(new_words)}")
    print(f"  Already in deck: {len(skipped_words)}")

    if not new_words:
        print("\nDeck is up to date — nothing to add.")
        return {
            "added": 0,
            "skipped": len(skipped_words),
            "audio_uploaded": 0,
            "words_added": [],
            "words_skipped": [w["word"] for w in skipped_words],
        }

    if dry_run:
        print(f"\n[DRY RUN] Would add:")
        for w in new_words:
            print(f"  + {w['word']}")
        return {
            "added": len(new_words),
            "skipped": len(skipped_words),
            "audio_uploaded": 0,
            "words_added": [w["word"] for w in new_words],
            "words_skipped": [w["word"] for w in skipped_words],
        }

    # 6. Generate audio and build notes for new words (parallel)
    if prefetch:
        print(f"\nPrefetching audio for {len(new_words)} new words (parallel)...")
    else:
        print(f"\nGenerating audio for {len(new_words)} new words (parallel)...")
    notes_to_add = []
    audio_uploads: list[tuple[str, bytes]] = []
    failed_words: list[str] = []
    word_ok = 0
    sent_ok = 0
    total = len(new_words)

    if audio_dir:
        # Load pre-generated audio from disk and build notes
        manifest_path = os.path.join(audio_dir, "manifest.json")
        if not os.path.isfile(manifest_path):
            print(f"Error: manifest not found at {manifest_path}", file=sys.stderr)
            sys.exit(1)
        with open(manifest_path, "r", encoding="utf-8") as mf:
            manifest = json.load(mf)
        # Restore notes (without deckName — fill in below)
        for idx, note in enumerate(manifest["notes"]):
            note["deckName"] = band_assignment.get(idx, deck_name)
            notes_to_add.append(note)
        # Load audio files from disk
        for filename, filepath in manifest["audio_files"].items():
            if os.path.isfile(filepath):
                with open(filepath, "rb") as af:
                    audio_uploads.append((filename, af.read()))
        word_ok = manifest["stats"]["word_ok"]
        sent_ok = manifest["stats"]["sent_ok"]
        print(f"  Loaded {len(notes_to_add)} notes + {len(audio_uploads)} audio files from cache")
    else:
        # Generate audio concurrently
        max_workers = min(16, len(new_words))
        if verbose:
            print(f"  ({max_workers} workers)")

        with concurrent.futures.ThreadPoolExecutor(max_workers=max_workers) as executor:
            future_map = {
                executor.submit(_process_one_word, w, book_id, no_audio): (idx, w)
                for idx, w in enumerate(new_words)
            }

            completed = 0
            for future in concurrent.futures.as_completed(future_map):
                idx, w = future_map[future]
                word = w["word"]
                lemma = lemmatize_word(word)
                completed += 1

                try:
                    note, word_audio, final_ipa = future.result()
                    note["deckName"] = band_assignment.get(idx, deck_name)
                    notes_to_add.append(note)
                    audio_uploads.extend(word_audio)

                    has_word = any(fn.endswith("_word.mp3") for fn, _ in word_audio)
                    has_sent = any(fn.endswith("_sent.mp3") for fn, _ in word_audio)
                    if has_word:
                        word_ok += 1
                    if has_sent:
                        sent_ok += 1

                    tag = f" ({lemma})" if lemma != word.lower() else ""
                    label = f"{word}{tag}"
                    if verbose and not no_audio:
                        parts = []
                        parts.append("word✓" if has_word else "word✗")
                        parts.append("sent✓" if has_sent else "sent✗")
                        label = f"{label}  audio: {', '.join(parts)}"
                    print_progress(completed, total, label)
                except Exception as e:
                    failed_words.append(word)
                    print()
                    print(f"  ✗ {word}: {e}")
                    print_progress(completed, total, word)

        print()

        # If prefetch mode: save to temp dir with manifest, then exit
        if prefetch:
            prefetch_dir = tempfile.mkdtemp(prefix="vocab_audio_")
            audio_files: dict[str, str] = {}

            for filename, data in audio_uploads:
                filepath = os.path.join(prefetch_dir, filename)
                with open(filepath, "wb") as af:
                    af.write(data)
                audio_files[filename] = filepath

            # Strip deckName from notes (will be filled in at sync time)
            saved_notes = []
            for note in notes_to_add:
                saved = dict(note)
                saved.pop("deckName", None)
                saved_notes.append(saved)

            manifest = {
                "notes": saved_notes,
                "audio_files": audio_files,
                "stats": {
                    "total": total,
                    "word_ok": word_ok,
                    "sent_ok": sent_ok,
                    "failed": len(failed_words),
                },
                "failed_words": failed_words,
            }
            manifest_path = os.path.join(prefetch_dir, "manifest.json")
            with open(manifest_path, "w", encoding="utf-8") as mf:
                json.dump(manifest, mf, indent=2, ensure_ascii=False)

            print(f"\nAudio prefetch complete:")
            print(f"  Word audio:  {word_ok}/{total}")
            print(f"  Sentence:    {sent_ok}/{total}")
            if failed_words:
                print(f"  Failed:      {len(failed_words)} ({', '.join(failed_words)})")
            print(f"\nAUDIO_DIR={prefetch_dir}")
            return {
                "added": 0,
                "skipped": len(skipped_words),
                "audio_uploaded": len(audio_uploads),
                "words_added": [],
                "words_skipped": [w["word"] for w in skipped_words],
                "failed_words": failed_words,
                "prefetch_dir": prefetch_dir,
                "prefetch_stats": manifest["stats"],
            }

    # 7. Upload media files (direct filesystem copy, fallback to AnkiConnect)
    audio_count = 0
    if audio_uploads and not dry_run:
        total_media = len(audio_uploads)
        media_dir = None if no_direct_media else _find_anki_media_dir()

        if media_dir:
            # Fast path: copy files directly into collection.media (~0.7s for 124 files)
            print(f"\nCopying {total_media} media files to Anki media dir...")
            if verbose:
                print(f"  {media_dir}")
            audio_count = _upload_media_direct(audio_uploads, media_dir, verbose=verbose)
            print()
            print(f"  Copied: {audio_count}/{total_media}")
        else:
            # Slow path: upload through AnkiConnect (per-file base64 + SQLite overhead)
            batch_size = 40
            print(f"\nUploading {total_media} media files via AnkiConnect (batched ×{batch_size})...")
            for batch_start in range(0, total_media, batch_size):
                batch = audio_uploads[batch_start:batch_start + batch_size]
                try:
                    results = ac.store_media_files_batch(batch, batch_size=batch_size)
                    for i, result in enumerate(results):
                        filename, audio_data = batch[i]
                        global_idx = batch_start + i + 1
                        if result is not None:
                            audio_count += 1
                            if verbose:
                                print_progress(global_idx, total_media, f"{filename} ({len(audio_data)} bytes)")
                            else:
                                print_progress(global_idx, total_media)
                        else:
                            print()
                            print(f"  ✗ {filename}: failed (duplicate or error)")
                            print_progress(global_idx, total_media)
                except AnkiConnectError as e:
                    for i, (filename, _data) in enumerate(batch):
                        global_idx = batch_start + i + 1
                        print()
                        print(f"  ✗ {filename}: {e}")
                        print_progress(global_idx, total_media)
            print()
            print(f"  Uploaded: {audio_count}/{total_media}")

    # 8. Add notes
    added_count = 0
    duped_count = 0
    if not dry_run and notes_to_add:
        print(f"\nAdding {len(notes_to_add)} new cards to Anki...")
        try:
            result = ac.add_notes(notes_to_add)
            added_count = sum(1 for r in result if r is not None)
            duped_count = sum(1 for r in result if r is None)
            print(f"  Added: {added_count}")
            if duped_count:
                print(f"  Duplicates (not added): {duped_count}")
        except AnkiConnectError as e:
            errmsg = str(e)
            if "duplicate" in errmsg.lower():
                print(f"  All {len(notes_to_add)} already exist (duplicates).")
                duped_count = len(notes_to_add)
            else:
                print(f"Error adding notes: {e}")
                return {
                    "added": 0,
                    "skipped": len(skipped_words),
                    "audio_uploaded": audio_count,
                    "words_added": [],
                    "words_skipped": [w["word"] for w in skipped_words + new_words],
                    "failed_words": failed_words,
                    "error": errmsg,
                }

    # 9. Trigger AnkiWeb sync (fire-and-forget)
    ankiweb_synced = False
    if ac and not no_ankiweb_sync and not dry_run:
        try:
            ac.sync()
            ankiweb_synced = True
            print(f"\nAnkiWeb sync triggered.")
        except AnkiConnectError as e:
            print(f"\nAnkiWeb sync skipped: {e}")

    # Summary
    print(f"\n{'='*50}")
    print(f"Sync complete for \"{book_title}\"")
    print(f"  New cards added:  {added_count}")
    print(f"  Already in deck:  {len(skipped_words)}")
    print(f"  Media uploaded:   {audio_count}")
    if data.get("excluded"):
        print(f"  Excluded (COCA):  {len(data.get('excluded', []))} word(s)")
    if failed_words:
        print(f"  Failed:           {len(failed_words)} word(s)")
        print(f"     ({', '.join(failed_words)})")
    print(f"{'='*50}")

    return {
        "added": added_count,
        "skipped": len(skipped_words),
        "audio_uploaded": audio_count,
        "words_added": [w["word"] for w in new_words[:added_count]],
        "words_skipped": [w["word"] for w in skipped_words],
        "failed_words": failed_words,
        "ankiweb_synced": ankiweb_synced,
    }


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------


def main() -> None:
    args = parse_args()

    # Read input
    with open(args.input_file, "r", encoding="utf-8") as f:
        data = json.load(f)

    # Basic validation
    if not data.get("book_title"):
        print("Error: missing 'book_title' in input", file=sys.stderr)
        sys.exit(1)
    if not data.get("book_id"):
        print("Error: missing 'book_id' in input", file=sys.stderr)
        sys.exit(1)
    if not data.get("words"):
        print("Error: 'words' array is empty", file=sys.stderr)
        sys.exit(1)

    # Deduplicate
    seen = set()
    deduped = []
    for w in data["words"]:
        key = w["word"].strip().lower()
        if key not in seen:
            seen.add(key)
            deduped.append(w)
    if len(deduped) < len(data["words"]):
        print(f"Note: deduplicated {len(data['words']) - len(deduped)} word(s)\n")
    data["words"] = deduped

    # Pre-fill IPA from cmudict before validation.
    # Claude may leave ipa empty — cmudict fills it automatically for known words.
    # Only words truly not in cmudict will still have empty ipa and fail validation
    # (requiring Claude to provide a manual IPA).
    for w in data["words"]:
        if not w.get("ipa", "").strip():
            json_lemma = w.get("lemma", "").strip()
            lookup_word = json_lemma if json_lemma else w["word"]
            cmu_ipa = _cmu_ipa(lookup_word)
            if cmu_ipa:
                w["ipa"] = cmu_ipa

    # Validate quality rules before sync
    errors = _validate_word_entries(data["words"])
    if errors:
        print(f"Quality check FAILED ({len(errors)} error(s)):", file=sys.stderr)
        for e in errors:
            print(f"  {e}", file=sys.stderr)
        sys.exit(1)

    # Deck name resolution priority:
    #   1. JSON deck_name field (set by Claude from Step 0b {deck: bookId} mapping)
    #   2. --deck CLI flag (explicit override)
    #   3. Auto-derive from book_title + book_author (new deck, fallback)
    json_deck = data.get("deck_name", "").strip()
    if json_deck:
        deck_name = json_deck
    elif args.deck:
        deck_name = args.deck
    else:
        author = data.get("book_author", "")
        title = data["book_title"]
        deck_name = f"{title} ({author})" if author else f"{title} Vocabulary"

    try:
        result = sync(
            data,
            deck_name,
            dry_run=args.dry_run,
            no_audio=args.no_audio,
            verbose=args.verbose,
            word_timeout=args.word_timeout,
            prefetch=args.prefetch,
            audio_dir=args.audio_dir,
            no_direct_media=args.no_direct_media,
            no_ankiweb_sync=args.no_ankiweb_sync,
            max_bands=args.max_bands,
            min_band_size=args.min_band_size,
        )
        if result.get("error"):
            sys.exit(1)
    except AnkiConnectError as e:
        print(f"\nError: {e}", file=sys.stderr)
        print(
            "\nMake sure:\n"
            "  1. Anki is running\n"
            '  2. AnkiConnect plugin is installed (add-on code: 2055492159)\n'
            "  3. The Vocabulary Card (WeRead) model exists in Anki\n"
            "     (import an .apkg file from this skill first)",
            file=sys.stderr,
        )
        sys.exit(1)


# ---------------------------------------------------------------------------
# ARPAbet → IPA conversion gold-standard tests
# ---------------------------------------------------------------------------


def _test_arpabet_to_ipa() -> None:
    """Verify ARPAbet→IPA mapping against known-correct gold standards.

    Never remove or weaken a test case — the mapping is the single source
    of truth for all card IPA generation.
    """
    failures = 0

    def check(word: str, expected: str) -> None:
        nonlocal failures
        got = _cmu_ipa(word)  # no Claude IPA → uses first entry
        if got != expected:
            failures += 1
            print(f"  FAIL: {word} → {got} (expected {expected})", file=sys.stderr)

    # ── Vowel length distinctions (tense vs lax) ──
    #   Monosyllabic: no stress mark (standard IPA convention)
    check("feed", "/fiːd/")          # IY → iː
    check("fed", "/fed/")            # EH → e
    check("fit", "/fɪt/")            # IH → ɪ
    check("food", "/fuːd/")          # UW → uː
    check("foot", "/fʊt/")           # UH → ʊ
    check("fast", "/fæst/")          # AE → æ
    check("father", "/fˈɑːðɜːr/")   # AA → ɑː, 2-syll → stress
    check("law", "/lɔː/")            # AO → ɔː, unambiguous in cmudict
    check("cup", "/kʌp/")            # AH → ʌ
    check("bird", "/bɜːrd/")         # ER → ɜːr

    # ── Diphthongs ──
    check("day", "/deɪ/")            # EY → eɪ
    check("go", "/ɡoʊ/")             # OW → oʊ
    check("my", "/maɪ/")             # AY → aɪ
    check("now", "/naʊ/")            # AW → aʊ
    check("boy", "/bɔɪ/")            # OY → ɔɪ

    # ── Consonants ──
    check("thin", "/θɪn/")           # TH → θ
    check("this", "/ðɪs/")           # DH → ð
    check("ship", "/ʃɪp/")           # SH → ʃ
    check("chip", "/tʃɪp/")          # CH → tʃ
    check("judge", "/dʒʌdʒ/")        # JH → dʒ
    check("sing", "/sɪŋ/")           # NG → ŋ
    check("measure", "/mˈeʒɜːr/")   # ZH → ʒ, 2-syll → stress
    check("yes", "/jes/")            # Y → j

    # ── Multi-syllable stress ──
    check("hunting", "/hˈʌntɪŋ/")
    check("accomplished", "/ʌkˈɑːmplɪʃt/")
    check("distinguished", "/dɪstˈɪŋɡwɪʃt/")
    check("beautiful", "/bjˈuːtʌfʌl/")
    check("blundering", "/blˈʌndɜːrɪŋ/")
    check("comfortable", "/kˈʌmfɜːrtʌbʌl/")

    if failures:
        print(f"\n  {failures} ARPAbet→IPA test(s) FAILED", file=sys.stderr)
        sys.exit(1)
    else:
        print(f"  ARPAbet→IPA: all {23+5} tests passed ✓")


if __name__ == "__main__":
    main()
