#!/usr/bin/env python3
"""Sync WeRead vocabulary words to Anki via AnkiConnect.

Reads JSON word data (same format as generate_apkg.py), connects to a
running Anki instance via AnkiConnect, compares against existing cards
in the target deck, and adds only *new* words. Existing cards are never
touched, preserving review history and scheduling.

Requires:
    - Anki running with the AnkiConnect plugin installed (code: 2055492159)
    - The "Vocabulary Card (WeRead)" model imported into Anki
      (import the .apkg generated by generate_apkg.py at least once)

Usage:
    python -m lib.sync_anki input.json
    python -m lib.sync_anki input.json --deck "Custom Deck Name"
    python -m lib.sync_anki input.json --dry-run
    python -m lib.sync_anki input.json --no-audio
"""

import argparse
import concurrent.futures
import glob
import json
import os
import platform
import re
import sys
import tempfile
import time

from .config import MIN_SENTENCE_LENGTH

from .ankiconnect import AnkiConnect, AnkiConnectError
from .audio import _find_anki_media_dir, _upload_media_direct, _repair_audio
from .ipa import _cmu_ipa
from .lemmatize import lemmatize
from .utils import (
    EDGE_TTS_MAX_RETRIES,
    edge_tts_bytes,
    print_progress,
    safe_filename,
)
from .validation import validate_word_entries

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

MODEL_NAME = "Vocabulary Card (WeRead)"
WORD_TIMEOUT = 30  # default seconds per word (audio generation)
# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Sync WeRead vocabulary to Anki via AnkiConnect"
    )
    parser.add_argument("input_file", help="JSON input file with word entries")
    parser.add_argument(
        "--deck", "-d", required=False, help="Target Anki deck name (auto-derived from JSON if omitted)"
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Show what would be added without actually adding",
    )
    parser.add_argument(
        "--no-audio",
        action="store_true",
        help="Skip audio generation and upload",
    )
    parser.add_argument(
        "--word-timeout",
        type=int,
        default=WORD_TIMEOUT,
        help=f"Max seconds per word for TTS audio generation (default: {WORD_TIMEOUT})",
    )
    parser.add_argument(
        "--prefetch",
        action="store_true",
        help="Generate audio concurrently and save to temp dir with manifest (no Anki interaction)",
    )
    parser.add_argument(
        "--audio-dir",
        required=False,
        help="Use pre-generated audio from directory (skips audio generation)",
    )
    parser.add_argument(
        "--no-direct-media",
        action="store_true",
        help="Always upload media via AnkiConnect API instead of direct filesystem copy",
    )
    parser.add_argument(
        "--no-ankiweb-sync",
        action="store_true",
        help="Skip triggering AnkiWeb sync after cards are added",
    )
    parser.add_argument(
        "-v", "--verbose", action="store_true", help="Show detailed progress"
    )
    return parser.parse_args()


# ---------------------------------------------------------------------------
# Utilities (reused from generate_apkg.py patterns)
# ---------------------------------------------------------------------------


# safe_filename(), edge_tts_bytes() imported from utils
# compute_bands(), _count_coca_levels(), _pre_assign_bands() imported from .bands


def _derive_deck_name(data: dict, cli_deck: str | None = None) -> str:
    """Derive Anki deck name from input JSON per resolution priority.

    1. JSON deck_name field (set by Claude from cardsInfo API)
    2. --deck CLI flag (explicit override)
    3. Auto-derive from book_title + book_author (fallback)
       - vocab-book mode (suffix present, no book_id): appends " - 分级词汇"
         to distinguish from vocab-anki flat deck, per SKILL.md spec
    """
    json_deck = data.get("deck_name", "").strip()
    if json_deck:
        return json_deck
    if cli_deck:
        return cli_deck

    author = data.get("book_author", "")
    title = data["book_title"]
    deck_name = f"{title} ({author})" if author else f"{title} Vocabulary"

    # vocab-book (suffix without book_id): add " - 分级词汇" suffix
    if data.get("suffix") and not data.get("book_id"):
        deck_name += " - 分级词汇"

    return deck_name


# _cmu_ipa() imported from .ipa


# ---------------------------------------------------------------------------
# Band / deck helpers (vocab-book)
# ---------------------------------------------------------------------------


def _compute_level_word_counts(words: list[dict]) -> dict[int, int]:
    """Count new words per COCA level from the input word list."""
    counts: dict[int, int] = {}
    for w in words:
        lvl = w.get("coca_level")
        if isinstance(lvl, int) and 1 <= lvl <= 25:
            counts[lvl] = counts.get(lvl, 0) + 1
    return counts


def _get_target_level_for_word(w: dict) -> int | None:
    """Get the target COCA level for a word (1-25 or None)."""
    lvl = w.get("coca_level")
    if isinstance(lvl, int) and 1 <= lvl <= 25:
        return lvl
    return None


def _compute_final_level_counts(
    words: list[dict],
    existing_map: dict[str, tuple[int, str]],
    namespace_id: str,
    bands: list[dict],
) -> dict[int, int]:
    """Compute final card count per COCA level after dedup.

    For each word: if WordId already exists → count at its current level
    (parsed from CocaLevel or deck name); if new → count at the
    word's target level.
    """
    # Build level → band mapping
    level_to_band: dict[int, tuple[int, int]] = {}
    for b in bands:
        for lvl in range(b["lo"], b["hi"] + 1):
            level_to_band[lvl] = (b["lo"], b["hi"])

    # Start with existing counts per level from the batch
    counts: dict[int, int] = {}
    for w in words:
        wid = _make_word_id(w, namespace_id)
        if wid in existing_map:
            lvl = w.get("coca_level")
            if isinstance(lvl, int) and 1 <= lvl <= 25:
                counts[lvl] = counts.get(lvl, 0) + 1
        else:
            lvl = _get_target_level_for_word(w)
            if lvl is not None:
                counts[lvl] = counts.get(lvl, 0) + 1
    return counts


def _build_subdeck_name(parent_deck: str, band: dict) -> str:
    """Build a full sub-deck path.

    e.g. "My Book - 分级词汇::COCA 3-5"
    """
    return f"{parent_deck}::{band['name']}"


def _print_deck_plan(
    data: dict,
    deck_name: str,
    new_word_counts: dict[int, int],
    bands: list[dict],
) -> None:
    """Print the deck plan — sub-deck names and word counts."""
    print(f"\n  Deck plan for \"{deck_name}\":")
    for band in bands:
        lo, hi = band["lo"], band["hi"]
        level_new = sum(
            c for lvl, c in new_word_counts.items() if lo <= lvl <= hi
        )
        print(f"    {band['name']}: {level_new} new words")
    print()


def _migrate_misplaced_cards(
    ac: "AnkiConnect",
    parent_deck: str,
    bands: list[dict],
    existing_map: dict | None = None,
) -> int:
    """Migrate ALL cards under parent to correct COCA sub-deck.

    Reads CocaLevel field from each card, determines target sub-deck,
    and moves cards that are in the wrong deck.  Returns count of
    migrated cards.
    """
    if existing_map is not None:
        existing = existing_map
    else:
        existing = ac.get_word_id_map_with_deck(parent_deck)
    if not existing:
        return 0

    # Build level → target sub-deck mapping (without count in name)
    level_to_target: dict[str, str] = {}  # coca_level_str → target deck prefix
    for band in bands:
        for lvl in range(band["lo"], band["hi"] + 1):
            prefix = f"{parent_deck}::{band['name']}"
            level_to_target[str(lvl)] = prefix

    # Get full note info to read CocaLevel
    all_note_ids = list({nid for nid, _deck in existing.values()})
    if not all_note_ids:
        return 0

    # Fetch CocaLevel from notesInfo
    info = ac.notes_info(all_note_ids)
    note_coca: dict[int, str] = {}
    for n in info:
        coca = (n.get("fields", {})
                 .get("CocaLevel", {})
                 .get("value", ""))
        note_coca[n["noteId"]] = coca

    migrated = 0
    for word_id, (note_id, current_deck) in existing.items():
        coca_str = note_coca.get(note_id, "")
        if not coca_str:
            continue
        target_prefix = level_to_target.get(coca_str)
        if not target_prefix:
            continue
        # Check if current deck exactly matches target deck
        if current_deck == target_prefix:
            continue  # Already in correct deck

        # Migrate: move cards to correct sub-deck
        try:
            card_ids = ac.get_cards_of_notes([note_id])
            if card_ids:
                ac.change_deck(card_ids, target_prefix)
                migrated += 1
        except AnkiConnectError:
            pass

    return migrated


def _make_word_id(word_data: dict, book_id: str,
                   resolved_lemma: str | None = None) -> str:
    """Compute the canonical WordId for a word entry.

    WordId = {safe_filename(resolved_lemma)}_{pos}_{book_id}

    POS is included to prevent collisions when the same lemma appears
    with different parts of speech (e.g. "walk" as NOUN vs VERB).
    """
    if resolved_lemma:
        resolved = resolved_lemma
    else:
        resolved = lemmatize(
            word_data["word"],
            json_lemma=word_data.get("lemma", ""),
        )
    pos = word_data.get("pos", "").strip()
    if pos:
        return f"{safe_filename(resolved)}_{pos}_{book_id}"
    return f"{safe_filename(resolved)}_{book_id}"


def _process_one_word(
    w: dict,
    book_id: str,
    no_audio: bool,
    word_timeout: int = WORD_TIMEOUT,
) -> tuple[dict, list[tuple[str, bytes]], str]:
    """Generate audio and build a note for a single word.

    Runs in a thread so it can be subject to a per-word timeout.

    Returns (note, audio_uploads, ipa).
    """
    word = w["word"]
    # Trust the lemma from match_sentences.py (authoritative, per-sentence spaCy analysis).
    # Falls back to the word itself if lemma is missing (degraded mode).
    lemma = w.get("lemma", "").strip() or word
    pos = w.get("pos", "").strip()
    pos_part = f"_{pos}" if pos else ""

    safe = safe_filename(lemma)

    # IPA: cmudict preferred.  Claude's IPA used as tiebreaker for
    # heteronyms (read/read, wound/wound) and fallback for OOV words.
    cmu_ipa = _cmu_ipa(lemma, w.get("ipa", ""))
    ipa = cmu_ipa if cmu_ipa else w.get("ipa", "")

    audio_uploads: list[tuple[str, bytes]] = []

    if not no_audio:
        # Word audio: Edge TTS on lemma (with IPA if available).
        #   Include book_id + POS — same lemma different POS (e.g.
        #   astray ADJ vs ADV) must not share audio filenames.
        tts_timeout = max(word_timeout // 2, 10)
        if ipa:
            tts = edge_tts_bytes(lemma, ipa=ipa, timeout=tts_timeout)
            if tts:
                audio_uploads.append((f"{safe}{pos_part}_{book_id}_word.mp3", tts))
            else:
                raise RuntimeError(
                    f"Word audio generation failed for '{lemma}' "
                    f"(TTS returned no data after {EDGE_TTS_MAX_RETRIES + 1} attempts)"
                )

        # Sentence audio: Edge TTS on cleaned sentence.
        #   Include book_id + POS in filename — different POS have
        #   different sentences and must not collide.
        clean = re.sub(r"<[^>]+>", "", w["sentence"])
        sent_tts = edge_tts_bytes(clean, timeout=tts_timeout)
        if sent_tts:
            audio_uploads.append((f"{safe}{pos_part}_{book_id}_sent.mp3", sent_tts))
        else:
            raise RuntimeError(
                f"Sentence audio generation failed for '{word}' "
                f"(TTS returned no data after {EDGE_TTS_MAX_RETRIES + 1} attempts)"
            )

    note = build_note_entry(w, ipa, book_id, lemma=lemma)
    # Preserve original index in new_words for correct band assignment.
    orig_idx = w.get("_idx")
    if orig_idx is not None:
        note["_idx"] = orig_idx
    return note, audio_uploads, ipa


def build_note_entry(
    word_data: dict,
    ipa: str | None,
    book_id: str,
    lemma: str | None = None,
) -> dict:
    """Build a single AnkiConnect note dict from word data.

    Audio files are referenced as [sound:filename.mp3] — the actual
    media files must be uploaded separately via store_media_file().

    If lemma is provided, it's used for the card Word field, audio
    filenames, and WordId.  WordId uses the resolved lemma for
    cross-book dedup consistency (see _make_word_id).
    """
    # WordId uses the resolved lemma — variants like "pondered" and
    # "pondering" map to the same WordId "ponder_{book_id}".
    # Use _make_word_id (single source of truth) so build_note_entry
    # and the dedup check always compute the same WordId.
    surface = word_data["word"].strip().lower()
    safe_lemma = safe_filename(lemma) if lemma else safe_filename(surface)
    word_id = _make_word_id(word_data, book_id, resolved_lemma=lemma)
    pos = word_data.get("pos", "").strip()
    pos_part = f"_{pos}" if pos else ""
    word_audio_ref = f"[sound:{safe_lemma}{pos_part}_{book_id}_word.mp3]"
    sent_audio_ref = f"[sound:{safe_lemma}{pos_part}_{book_id}_sent.mp3]"

    # Insert <b> tags around the target word using target_offset.
    # Sentence is stored without tags — we add them here for Anki display.
    # Use the original-casing word (not lowercased surface) for the tag text.
    sent = word_data.get("sentence", "")
    target_offset = word_data.get("target_offset", -1)
    display_word = word_data["word"]  # original casing from sentence
    if target_offset >= 0 and target_offset + len(display_word) <= len(sent):
        sent = (
            sent[:target_offset]
            + f"<b>{display_word}</b>"
            + sent[target_offset + len(display_word):]
        )

    coca_level = str(word_data.get("coca_level", ""))
    return {
        "deckName": "",  # filled in later by caller
        "modelName": MODEL_NAME,
        "fields": {
            "WordId": word_id,
            "Word": lemma if lemma else surface,
            "Sentence": sent,
            "IPA": ipa or word_data.get("ipa", ""),
            "DefinitionCN": word_data["definition_cn"],
            "TranslationCN": word_data["translation_cn"],
            "WordAudio": word_audio_ref,
            "SentenceAudio": sent_audio_ref,
            "CocaLevel": coca_level,
        },
        "tags": ["weread"],
    }


# _validate_word_entries() imported from .validation
# _find_anki_media_dir(), _upload_media_direct(), _repair_audio() imported from .audio

def _dummy_removed() -> None:  # placeholder — real code moved to validation.py + audio.py
    pass


# _validate_word_entries() imported from .validation
# _find_anki_media_dir(), _upload_media_direct(), _repair_audio() imported from .audio

def sync(
    data: dict,
    deck_name: str,
    dry_run: bool = False,
    no_audio: bool = False,
    verbose: bool = False,
    word_timeout: int = WORD_TIMEOUT,
    prefetch: bool = False,
    audio_dir: str | None = None,
    no_direct_media: bool = False,
    no_ankiweb_sync: bool = False,
) -> dict:
    """Run the full sync workflow. Returns a summary dict."""
    words = data["words"]
    book_title = data["book_title"]

    # 命名空间标识，用于 WordId / 音频文件名隔离
    #   vocab-anki: 微信读书 bookId（如 "22720170"）
    #   vocab-book: filter_fulltext.py 生成的 UUID suffix（如 "a1b2c3d4e5f6"）
    namespace_id = data.get("book_id", "") or data.get("suffix", "")

    # Read bands from JSON (set by filter_fulltext.py)
    bands: list[dict] = data.get("bands", [])

    # 1. Connect to Anki (skip for prefetch — audio-only mode)
    ac = None
    existing_map: dict[str, tuple[int, str]] = {}

    if not prefetch:
        print('Connecting to AnkiConnect...')
        ac = AnkiConnect()
        # Pre-flight: fail fast before any heavy work (audio, deck creation)
        try:
            ac.version()
        except AnkiConnectError as e:
            print(f"FATAL: {e}", file=sys.stderr)
            sys.exit(1)

        # Auto-correct deck name by bookId
        if namespace_id:
            found_deck, count = ac.find_deck_for_book_id(namespace_id)
            if found_deck and found_deck != deck_name:
                resolved = found_deck
                if "::" in resolved:
                    resolved = resolved.split("::")[0]
                if data.get("book_id") and not data.get("suffix"):
                    if resolved.endswith(" - 分级词汇"):
                        resolved = resolved[:-len(" - 分级词汇")]
                if resolved != deck_name:
                    print(f'  Note: using existing deck "{resolved}" '
                          f'(found {count} cards with bookId={namespace_id})')
                    deck_name = resolved

        # 2. Create parent deck
        if not dry_run:
            ac.ensure_deck_and_model(deck_name, MODEL_NAME)
        print(f'  Deck: "{deck_name}"')

        # 3. Parent-level dedup: query all cards across all sub-decks
        if bands:
            print("\nQuerying existing cards across all sub-decks...")
            existing_map = ac.get_word_id_map_with_deck(deck_name)
            print(f"  Found {len(existing_map)} existing cards in parent deck")
        else:
            # No bands → flat deck
            existing_word_ids = ac.get_word_id_map(deck_name)
            existing_map = {
                wid: (nid, deck_name)
                for wid, nid in existing_word_ids.items()
            }
            print(f"  Found {len(existing_map)} existing cards")
    else:
        existing_map = {}  # prefetch: skip live Anki query; _already_in_anki markers handle filtering

    # 4. Compute new word counts per level and build target deck mapping
    level_new_counts = _compute_level_word_counts(words)
    word_target_deck: dict[int, str] = {}  # idx in new_words → target deck

    # Build level→band index for assignment
    level_to_band: dict[int, dict] = {}
    for band in bands:
        for lvl in range(band["lo"], band["hi"] + 1):
            level_to_band[lvl] = band

    # 5. Identify new words + migration candidates (parent-level dedup)
    new_words = []
    skipped_words = []
    seen_word_ids: set[str] = set()

    for idx, w in enumerate(words):
        word_id = _make_word_id(w, namespace_id)

        # Intra-batch dedup
        if word_id in seen_word_ids:
            if verbose:
                print(f"  SKIP {w['word']} (duplicate lemma in batch → {word_id})")
            skipped_words.append(w)
            continue
        seen_word_ids.add(word_id)

        # Pre-dedup: Step 2A-post marks words already known to be in Anki.
        # (sentence, word) key is stable across POS/lemma changes.
        # Applies in both prefetch and sync modes — in prefetch mode this
        # avoids generating audio for words that already have cards.
        if w.get('_already_in_anki'):
            if verbose:
                print(f"  SKIP {w['word']} (already in Anki, from Step 2A-post dedup)")
            skipped_words.append(w)
            continue

        # Parent-level dedup: check across all sub-decks
        if word_id in existing_map:
            if verbose:
                print(f"  SKIP {w['word']} (already in deck)")
            skipped_words.append(w)
        else:
            new_words.append(w)

    # Assign target deck for each new word.
    # Also build a WordId→target_deck mapping for the audio_dir path
    # where manifest _idx may not match sync-time new_words ordering
    # (prefetch has empty existing_map, so new_words differs).
    word_id_to_target_deck: dict[str, str] = {}
    for idx, w in enumerate(new_words):
        lvl = _get_target_level_for_word(w)
        if lvl is not None and lvl in level_to_band:
            band = level_to_band[lvl]
            target_name = _build_subdeck_name(deck_name, band)
            word_target_deck[idx] = target_name
        else:
            target_name = deck_name  # parent deck fallback
            word_target_deck[idx] = target_name
        word_id_to_target_deck[_make_word_id(w, namespace_id)] = target_name

    # 6. Print deck plan (informational, doesn't block)
    if bands:
        _print_deck_plan(data, deck_name, level_new_counts, bands)

    # Print level distribution
    if bands:
        level_dist: dict[str, int] = {}
        for deck in word_target_deck.values():
            short = deck.split("::")[-1] if "::" in deck else deck
            level_dist[short] = level_dist.get(short, 0) + 1
        print(f"  New word distribution: "
              f"{', '.join(f'{k}: {v}' for k, v in level_dist.items())}")

    print(f"\n  New words to add: {len(new_words)}")
    print(f"  Already in deck: {len(skipped_words)}")

    # 7. Create sub-decks
    if bands and not prefetch and not dry_run:
        for band in bands:
            sub_deck = _build_subdeck_name(deck_name, band)
            ac.ensure_deck_and_model(sub_deck, MODEL_NAME)

    # 8. Migrate misplaced cards
    migration_count = 0
    if bands and not prefetch and not dry_run:
        print(f"\nChecking for misplaced cards...")
        migration_count = _migrate_misplaced_cards(ac, deck_name, bands, existing_map)
        if migration_count:
            print(f"  Migrated {migration_count} card(s) to correct sub-decks")

    if not new_words:
        print("\nDeck is up to date — nothing to add.")
        return {
            "added": 0,
            "skipped": len(skipped_words),
            "audio_uploaded": 0,
            "words_added": [],
            "words_skipped": [w["word"] for w in skipped_words],
            "migrated": migration_count,
        }

    if dry_run:
        print(f"\n[DRY RUN] Would add:")
        for w in new_words:
            print(f"  + {w['word']}")
        return {
            "added": len(new_words),
            "skipped": len(skipped_words),
            "audio_uploaded": 0,
            "words_added": [w["word"] for w in new_words],
            "words_skipped": [w["word"] for w in skipped_words],
        }

    # 9. Generate audio and build notes for new words (parallel)
    if prefetch:
        print(f"\nPrefetching audio for {len(new_words)} new words (parallel)...")
    else:
        print(f"\nGenerating audio for {len(new_words)} new words (parallel)...")
    notes_to_add = []
    audio_uploads: list[tuple[str, bytes]] = []
    failed_words: list[str] = []
    word_ok = 0
    sent_ok = 0
    total = len(new_words)

    if audio_dir:
        # Load pre-generated audio from disk and build notes
        manifest_path = os.path.join(audio_dir, "manifest.json")
        if not os.path.isfile(manifest_path):
            print(f"Error: manifest not found at {manifest_path}", file=sys.stderr)
            sys.exit(1)
        with open(manifest_path, "r", encoding="utf-8") as mf:
            manifest = json.load(mf)
        # Restore notes (without deckName — fill in below).
        # Match by WordId (not _idx) because prefetch has empty
        # existing_map so its new_words/index differ from sync.
        # Only load notes for words in the current new_words set —
        # the manifest may contain stale entries from a previous
        # prefetch run that included already-known words.
        new_word_ids = {_make_word_id(w, namespace_id) for w in new_words}
        for i, note in enumerate(manifest["notes"]):
            wid = note.get("fields", {}).get("WordId", "")
            if wid and wid not in new_word_ids:
                continue  # stale entry from a different prefetch batch
            note["deckName"] = word_id_to_target_deck.get(
                wid,
                word_target_deck.get(note.get("_idx", i), deck_name),
            )
            notes_to_add.append(note)
        # Load audio files from disk — filter against new_word_ids.
        # Audio filenames: {safe_lemma}_{POS}_{book_id}_word.mp3 or _sent.mp3
        # WordId = {safe_filename(lemma)}_{POS}_{book_id}, same as filename prefix.
        for filename, filepath in manifest["audio_files"].items():
            if filename.endswith("_word.mp3"):
                wid = filename[:-len("_word.mp3")]
            elif filename.endswith("_sent.mp3"):
                wid = filename[:-len("_sent.mp3")]
            else:
                continue  # unknown pattern, skip
            if wid not in new_word_ids:
                if verbose:
                    print(f"  SKIP audio {filename} (stale — WordId not in new_words)")
                continue
            if os.path.isfile(filepath):
                with open(filepath, "rb") as af:
                    audio_uploads.append((filename, af.read()))
        word_ok = manifest["stats"]["word_ok"]
        sent_ok = manifest["stats"]["sent_ok"]
        print(f"  Loaded {len(notes_to_add)} notes + {len(audio_uploads)} audio files from cache")
    else:
        # Generate audio concurrently
        max_workers = min(16, len(new_words))
        if verbose:
            print(f"  ({max_workers} workers)")

        # Inject _idx before thread pool so each note preserves its
        # original position for correct band assignment.
        for idx, w in enumerate(new_words):
            w["_idx"] = idx

        with concurrent.futures.ThreadPoolExecutor(max_workers=max_workers) as executor:
            future_map = {
                executor.submit(_process_one_word, w, namespace_id, no_audio, word_timeout): (idx, w)
                for idx, w in enumerate(new_words)
            }

            completed = 0
            for future in concurrent.futures.as_completed(future_map):
                idx, w = future_map[future]
                word = w["word"]
                lemma = w.get("lemma", "").strip() or word
                completed += 1

                try:
                    note, word_audio, final_ipa = future.result(timeout=word_timeout)
                    note["deckName"] = word_target_deck.get(idx, deck_name)
                    notes_to_add.append(note)
                    audio_uploads.extend(word_audio)

                    has_word = any(fn.endswith("_word.mp3") for fn, _ in word_audio)
                    has_sent = any(fn.endswith("_sent.mp3") for fn, _ in word_audio)
                    if has_word:
                        word_ok += 1
                    if has_sent:
                        sent_ok += 1

                    tag = f" ({lemma})" if lemma != word.lower() else ""
                    label = f"{word}{tag}"
                    if verbose and not no_audio:
                        parts = []
                        parts.append("word✓" if has_word else "word✗")
                        parts.append("sent✓" if has_sent else "sent✗")
                        label = f"{label}  audio: {', '.join(parts)}"
                    print_progress(completed, total, label)
                except Exception as e:
                    failed_words.append(word)
                    print()
                    print(f"  ✗ {word}: {e}")
                    print_progress(completed, total, word)

        print()

        # Mechanical check: verify every note's WordId matches _make_word_id.
        # This catches drift between build_note_entry and the dedup check —
        # both must use the same resolved-lemma WordId format.
        for note in notes_to_add:
            wid = note["fields"]["WordId"]
            # Reconstruct expected WordId from the same input that
            # build_note_entry received.  We don't have the original
            # word_data here, so validate by checking the WordId uses
            # the safe_filename(Word) pattern (Word field = resolve_lemma result).
            card_word = note["fields"]["Word"]
            expected_prefix = safe_filename(card_word)
            if not wid.startswith(expected_prefix + "_"):
                raise AssertionError(
                    f"WordId mismatch: note WordId={wid!r} but card Word={card_word!r} "
                    f"(expected WordId to start with {expected_prefix!r}_)"
                )

        # If prefetch mode: save to temp dir with manifest, then exit
        if prefetch:
            prefetch_dir = tempfile.mkdtemp(prefix="vocab_audio_")
            audio_files: dict[str, str] = {}

            for filename, data in audio_uploads:
                filepath = os.path.join(prefetch_dir, filename)
                with open(filepath, "wb") as af:
                    af.write(data)
                audio_files[filename] = filepath

            # Strip deckName from notes (will be filled in at sync time)
            saved_notes = []
            for note in notes_to_add:
                saved = dict(note)
                saved.pop("deckName", None)
                saved_notes.append(saved)

            manifest = {
                "notes": saved_notes,
                "audio_files": audio_files,
                "stats": {
                    "total": total,
                    "word_ok": word_ok,
                    "sent_ok": sent_ok,
                    "failed": len(failed_words),
                },
                "failed_words": failed_words,
            }
            manifest_path = os.path.join(prefetch_dir, "manifest.json")
            with open(manifest_path, "w", encoding="utf-8") as mf:
                json.dump(manifest, mf, indent=2, ensure_ascii=False)

            print(f"\nAudio prefetch complete:")
            print(f"  Word audio:  {word_ok}/{total}")
            print(f"  Sentence:    {sent_ok}/{total}")
            if failed_words:
                raise RuntimeError(
                    f"Audio generation failed for {len(failed_words)} word(s) "
                    f"after {EDGE_TTS_MAX_RETRIES + 1} attempts each: "
                    f"{', '.join(failed_words)}"
                )
            print(f"\nAUDIO_DIR={prefetch_dir}")
            return {
                "added": 0,
                "skipped": len(skipped_words),
                "audio_uploaded": len(audio_uploads),
                "words_added": [],
                "words_skipped": [w["word"] for w in skipped_words],
                "failed_words": failed_words,
                "prefetch_dir": prefetch_dir,
                "prefetch_stats": manifest["stats"],
            }

    # 7. Upload media files (direct filesystem copy, fallback to AnkiConnect)
    audio_count = 0
    if audio_uploads and not dry_run:
        total_media = len(audio_uploads)
        media_dir = None if no_direct_media else _find_anki_media_dir()

        if media_dir:
            # Fast path: copy files directly into collection.media (~0.7s for 124 files)
            print(f"\nCopying {total_media} media files to Anki media dir...")
            if verbose:
                print(f"  {media_dir}")
            audio_count = _upload_media_direct(audio_uploads, media_dir, verbose=verbose)
            print()
            print(f"  Copied: {audio_count}/{total_media}")
        else:
            # Slow path: upload through AnkiConnect (per-file base64 + SQLite overhead)
            batch_size = 40
            print(f"\nUploading {total_media} media files via AnkiConnect (batched ×{batch_size})...")
            for batch_start in range(0, total_media, batch_size):
                batch = audio_uploads[batch_start:batch_start + batch_size]
                try:
                    results = ac.store_media_files_batch(batch, batch_size=batch_size)
                    for i, result in enumerate(results):
                        filename, audio_data = batch[i]
                        global_idx = batch_start + i + 1
                        if result is not None:
                            audio_count += 1
                            if verbose:
                                print_progress(global_idx, total_media, f"{filename} ({len(audio_data)} bytes)")
                            else:
                                print_progress(global_idx, total_media)
                        else:
                            print()
                            print(f"  ✗ {filename}: failed (duplicate or error)")
                            print_progress(global_idx, total_media)
                except AnkiConnectError as e:
                    for i, (filename, _data) in enumerate(batch):
                        global_idx = batch_start + i + 1
                        print()
                        print(f"  ✗ {filename}: {e}")
                        print_progress(global_idx, total_media)
            print()
            print(f"  Uploaded: {audio_count}/{total_media}")

    # 8. Add notes
    added_count = 0
    duped_count = 0
    if not dry_run and notes_to_add:
        print(f"\nAdding {len(notes_to_add)} new cards to Anki...")
        try:
            # Strip internal _idx before sending to AnkiConnect
            for note in notes_to_add:
                note.pop("_idx", None)
            result = ac.add_notes(notes_to_add)
            added_count = sum(1 for r in result if r is not None)
            duped_count = sum(1 for r in result if r is None)
            print(f"  Added: {added_count}")
            if duped_count:
                print(f"  Duplicates (not added): {duped_count}")
        except AnkiConnectError as e:
            errmsg = str(e)
            if "duplicate" in errmsg.lower():
                print(f"  All {len(notes_to_add)} already exist (duplicates).")
                duped_count = len(notes_to_add)
            else:
                print(f"Error adding notes: {e}")
                return {
                    "added": 0,
                    "skipped": len(skipped_words),
                    "audio_uploaded": audio_count,
                    "words_added": [],
                    "words_skipped": [w["word"] for w in skipped_words + new_words],
                    "failed_words": failed_words,
                    "error": errmsg,
                }

    # 9. Trigger AnkiWeb sync (fire-and-forget)
    ankiweb_synced = False
    if ac and not no_ankiweb_sync and not dry_run:
        try:
            ac.sync()
            ankiweb_synced = True
            print(f"\nAnkiWeb sync triggered.")
        except AnkiConnectError as e:
            print(f"\nAnkiWeb sync skipped: {e}")

    # Summary
    print(f"\n{'='*50}")
    print(f"Sync complete for \"{book_title}\"")
    print(f"  New cards added:  {added_count}")
    print(f"  Already in deck:  {len(skipped_words)}")
    print(f"  Media uploaded:   {audio_count}")
    if data.get("excluded"):
        print(f"  Excluded (COCA):  {len(data.get('excluded', []))} word(s)")
    if failed_words:
        raise RuntimeError(
            f"Audio generation failed for {len(failed_words)} word(s) "
            f"after {EDGE_TTS_MAX_RETRIES + 1} attempts each: "
            f"{', '.join(failed_words)}"
        )
    print(f"{'='*50}")

    return {
        "added": added_count,
        "skipped": len(skipped_words),
        "audio_uploaded": audio_count,
        "words_added": [w["word"] for w in new_words[:added_count]],
        "words_skipped": [w["word"] for w in skipped_words],
        "failed_words": failed_words,
        "ankiweb_synced": ankiweb_synced,
    }


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------


def main() -> None:
    args = parse_args()

    # Read input
    with open(args.input_file, "r", encoding="utf-8") as f:
        data = json.load(f)

    # Basic validation
    if not data.get("book_title"):
        print("Error: missing 'book_title' in input", file=sys.stderr)
        sys.exit(1)
    if not data.get("book_id") and not data.get("suffix"):
        print("Error: missing 'book_id' or 'suffix' in input", file=sys.stderr)
        sys.exit(1)
    if not data.get("words"):
        print("Error: 'words' array is empty", file=sys.stderr)
        sys.exit(1)

    def _better_sentence(old: dict, new: dict) -> bool:
        """Return True if *new* entry has a better sentence than *old*.

        Same logic as match_sentences._better():
          Tier 0: non-fragment beats fragment (is_fragment=False > True)
          Otherwise: shorter wins above MIN_SENTENCE_LENGTH (30);
                     longer wins below it.
          Tie (same length): keep old.
        """
        # Tier 0 — completeness: non-fragment beats fragment
        old_frag = old.get('is_fragment', False)
        new_frag = new.get('is_fragment', False)
        if old_frag != new_frag:
            return not new_frag  # pick new only if it's complete

        la = len(old.get('sentence', ''))
        lb = len(new.get('sentence', ''))
        if la == lb:
            return False  # tie → keep old
        if (la < MIN_SENTENCE_LENGTH or lb < MIN_SENTENCE_LENGTH) ^ (la < lb):
            return False  # keep old
        return True  # pick new

    # Deduplicate by (lemma, pos) — not by surface word form.
    # WordId = {lemma}_{pos}_{suffix}, POS is included precisely so that
    # the same lemma with different POS (e.g. astray ADJ vs ADV,
    # virgin ADJ vs NOUN) produces separate cards.
    # When collisions occur, _better_sentence() keeps the entry with
    # the better sentence (shorter in sweet-spot, non-fragment beats
    # fragment), matching match_sentences.py's sentence selection.
    seen: dict[tuple[str, str], dict] = {}
    deduped = []
    dedup_details: list[str] = []
    for w in data["words"]:
        key = (w["lemma"].strip().lower(), w["pos"].strip().upper())
        if key not in seen:
            seen[key] = w
        else:
            existing = seen[key]
            if _better_sentence(existing, w):
                dedup_details.append(
                    f"    {existing.get('word', '?')} "
                    f"→ replaced by {w.get('word', '?')} "
                    f"(better sentence: "
                    f"{len(existing.get('sentence',''))} → {len(w.get('sentence',''))} chars)"
                )
                seen[key] = w
            else:
                dedup_details.append(
                    f"    {w.get('word', '?')} "
                    f"(lemma={w.get('lemma', '?')}, "
                    f"pos={w.get('pos', '?')}) — dropped, kept {existing.get('word', '?')}"
                )
    deduped = list(seen.values())
    if len(deduped) < len(data["words"]):
        dropped = len(data["words"]) - len(deduped)
        print(f"\n[DEDUP] {dropped} duplicate (lemma, pos) entries "
              f"dropped from batch:")
        for detail in dedup_details:
            print(detail, file=sys.stderr)
        print(
            "  This may indicate Step 2F POS fix collisions. "
            "Review the dropped entries and adjust POS if needed.\n",
            file=sys.stderr,
        )
    data["words"] = deduped

    # Verify no two entries share the same audio filename prefix.
    # The prefix is {safe_filename(lemma)}_{pos} — same prefix means
    # both word and sentence audio files would collide.
    # This is a defense-in-depth check: the (lemma,pos) dedup above
    # should prevent this, but a bug in dedup logic could silently
    # produce audio collisions (see commit 64c0b18).
    audio_keys: dict[str, list[str]] = {}
    for w in data["words"]:
        lemma = w.get("lemma", "").strip() or w["word"]
        pos = w.get("pos", "").strip()
        safe = safe_filename(lemma)
        prefix = f"{safe}_{pos}" if pos else safe
        if prefix not in audio_keys:
            audio_keys[prefix] = []
        audio_keys[prefix].append(w["word"])
    collisions = {k: v for k, v in audio_keys.items() if len(v) > 1}
    if collisions:
        print("Error: audio filename collision detected:", file=sys.stderr)
        for prefix, words in collisions.items():
            print(f"  prefix '{prefix}_*': {len(words)} words — {', '.join(words)}",
                  file=sys.stderr)
        print("  Each (lemma,pos) must have a unique audio prefix. "
              "Check dedup logic.", file=sys.stderr)
        sys.exit(1)

    # Pre-fill IPA from cmudict before validation.
    # Claude may leave ipa empty — cmudict fills it automatically for known words.
    # Only words truly not in cmudict will still have empty ipa and fail validation
    # (requiring Claude to provide a manual IPA).
    for w in data["words"]:
        if not w.get("ipa", "").strip():
            json_lemma = w.get("lemma", "").strip()
            lookup_word = json_lemma if json_lemma else w["word"]
            cmu_ipa = _cmu_ipa(lookup_word)
            if cmu_ipa:
                w["ipa"] = cmu_ipa

    # Validate quality rules before sync — only entries that will be
    # processed (skip _already_in_anki entries whose fields were not re-generated)
    active_words = [w for w in data["words"] if not w.get("_already_in_anki")]
    errors = validate_word_entries(active_words)
    if errors:
        print(f"Quality check FAILED ({len(errors)} error(s)):", file=sys.stderr)
        for e in errors:
            print(f"  {e}", file=sys.stderr)
        sys.exit(1)

    # Deck name resolution priority:
    #   1. Anki existing deck by bookId (sync() auto-corrects via
    #      find_deck_for_book_id — prevents accent/spelling drift)
    #   2. JSON deck_name field (set by Claude from Step 0b
    #      {deck: bookId} mapping via cardsInfo API)
    #   3. --deck CLI flag (explicit override)
    #   4. Auto-derive from book_title + book_author (new deck, fallback)
    #      vocab-book mode (suffix w/o book_id) appends " - 分级词汇"
    deck_name = _derive_deck_name(data, args.deck)

    try:
        result = sync(
            data,
            deck_name,
            dry_run=args.dry_run,
            no_audio=args.no_audio,
            verbose=args.verbose,
            word_timeout=args.word_timeout,
            prefetch=args.prefetch,
            audio_dir=args.audio_dir,
            no_direct_media=args.no_direct_media,
            no_ankiweb_sync=args.no_ankiweb_sync,
        )
        if result.get("error"):
            sys.exit(1)
    except AnkiConnectError as e:
        print(f"\nError: {e}", file=sys.stderr)
        print(
            "\nMake sure:\n"
            "  1. Anki is running\n"
            '  2. AnkiConnect plugin is installed (add-on code: 2055492159)\n'
            "  3. The Vocabulary Card (WeRead) model exists in Anki\n"
            "     (import an .apkg file from this skill first)",
            file=sys.stderr,
        )
        sys.exit(1)


# ---------------------------------------------------------------------------
# ARPAbet → IPA conversion gold-standard tests
# ---------------------------------------------------------------------------


def _test_arpabet_to_ipa() -> None:
    """Verify ARPAbet→IPA mapping against known-correct gold standards.

    Never remove or weaken a test case — the mapping is the single source
    of truth for all card IPA generation.
    """
    failures = 0

    def check(word: str, expected: str) -> None:
        nonlocal failures
        got = _cmu_ipa(word)  # no Claude IPA → uses first entry
        if got != expected:
            failures += 1
            print(f"  FAIL: {word} → {got} (expected {expected})", file=sys.stderr)

    # ── Vowel length distinctions (tense vs lax) ──
    #   Monosyllabic: no stress mark (standard IPA convention)
    check("feed", "/fiːd/")          # IY → iː
    check("fed", "/fed/")            # EH → e
    check("fit", "/fɪt/")            # IH → ɪ
    check("food", "/fuːd/")          # UW → uː
    check("foot", "/fʊt/")           # UH → ʊ
    check("fast", "/fæst/")          # AE → æ
    check("father", "/ˈfɑːðər/")     # AA → ɑː, ER0 → ər
    check("law", "/lɔː/")            # AO → ɔː, unambiguous in cmudict
    check("cup", "/kʌp/")            # AH → ʌ
    check("bird", "/bɜːrd/")         # ER1 → ɜːr (monosyllabic, no stress)

    # ── Diphthongs ──
    check("day", "/deɪ/")            # EY → eɪ
    check("go", "/ɡoʊ/")             # OW → oʊ
    check("my", "/maɪ/")             # AY → aɪ
    check("now", "/naʊ/")            # AW → aʊ
    check("boy", "/bɔɪ/")            # OY → ɔɪ

    # ── Consonants ──
    check("thin", "/θɪn/")           # TH → θ
    check("this", "/ðɪs/")           # DH → ð
    check("ship", "/ʃɪp/")           # SH → ʃ
    check("chip", "/tʃɪp/")          # CH → tʃ
    check("judge", "/dʒʌdʒ/")        # JH → dʒ
    check("sing", "/sɪŋ/")           # NG → ŋ
    check("measure", "/ˈmeʒər/")     # ZH → ʒ, ER0 → ər
    check("yes", "/jes/")            # Y → j

    # ── Multi-syllable stress ──
    check("hunting", "/ˈhʌntɪŋ/")
    check("accomplished", "/əˈkɑːmplɪʃt/")
    check("distinguished", "/dɪˈstɪŋɡwɪʃt/")
    check("beautiful", "/ˈbjuːtəfəl/")
    check("blundering", "/ˈblʌndərɪŋ/")
    check("comfortable", "/ˈkʌmfərtəbəl/")

    if failures:
        print(f"\n  {failures} ARPAbet→IPA test(s) FAILED", file=sys.stderr)
        sys.exit(1)
    else:
        print(f"  ARPAbet→IPA: all {29} tests passed ✓")


if __name__ == "__main__":
    main()
