#!/usr/bin/env python3
"""Sync WeRead vocabulary words to Anki via AnkiConnect.

Reads JSON word data (same format as generate_apkg.py), connects to a
running Anki instance via AnkiConnect, compares against existing cards
in the target deck, and adds only *new* words. Existing cards are never
touched, preserving review history and scheduling.

Requires:
    - Anki running with the AnkiConnect plugin installed (code: 2055492159)
    - The "Vocabulary Card (WeRead)" model imported into Anki
      (import the .apkg generated by generate_apkg.py at least once)

Usage:
    python sync_anki.py input.json
    python sync_anki.py input.json --deck "Custom Deck Name"
    python sync_anki.py input.json --dry-run
    python sync_anki.py input.json --no-audio
"""

import argparse
import concurrent.futures
import glob
import json
import os
import platform
import re
import sys
import tempfile
import time

from .ankiconnect import AnkiConnect, AnkiConnectError
from .audio import _find_anki_media_dir, _upload_media_direct, _repair_audio
from .bands import compute_bands, _count_coca_levels, _pre_assign_bands
from .config import MAX_SENTENCE_LENGTH
from .ipa import _cmu_ipa
from .lemmatize import lemmatize
from .utils import (
    EDGE_TTS_MAX_RETRIES,
    _get_spacy,
    edge_tts_bytes,
    lemmatize_word,
    print_progress,
    safe_filename,
)
from .validation import validate_word_entries

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

MODEL_NAME = "Vocabulary Card (WeRead)"
WORD_TIMEOUT = 30  # default seconds per word (audio generation)
# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Sync WeRead vocabulary to Anki via AnkiConnect"
    )
    parser.add_argument("input_file", help="JSON input file with word entries")
    parser.add_argument(
        "--deck", "-d", required=False, help="Target Anki deck name (auto-derived from JSON if omitted)"
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Show what would be added without actually adding",
    )
    parser.add_argument(
        "--no-audio",
        action="store_true",
        help="Skip audio generation and upload",
    )
    parser.add_argument(
        "--word-timeout",
        type=int,
        default=WORD_TIMEOUT,
        help=f"Deprecated. API calls have built-in timeouts. (default: {WORD_TIMEOUT})",
    )
    parser.add_argument(
        "--prefetch",
        action="store_true",
        help="Generate audio concurrently and save to temp dir with manifest (no Anki interaction)",
    )
    parser.add_argument(
        "--audio-dir",
        required=False,
        help="Use pre-generated audio from directory (skips audio generation)",
    )
    parser.add_argument(
        "--no-direct-media",
        action="store_true",
        help="Always upload media via AnkiConnect API instead of direct filesystem copy",
    )
    parser.add_argument(
        "--no-ankiweb-sync",
        action="store_true",
        help="Skip triggering AnkiWeb sync after cards are added",
    )
    parser.add_argument(
        "--max-bands",
        type=int,
        default=5,
        help="Maximum number of COCA frequency sub-decks (default: 5)",
    )
    parser.add_argument(
        "--min-band-size",
        type=int,
        default=100,
        help="Minimum words per frequency band (default: 100)",
    )
    parser.add_argument(
        "-v", "--verbose", action="store_true", help="Show detailed progress"
    )
    return parser.parse_args()


# ---------------------------------------------------------------------------
# Utilities (reused from generate_apkg.py patterns)
# ---------------------------------------------------------------------------


# safe_filename(), edge_tts_bytes() imported from utils
# compute_bands(), _count_coca_levels(), _pre_assign_bands() imported from .bands


def _get_existing_per_deck(
    ac: "AnkiConnect",  # noqa: F821
    deck_name: str,
    bands: list[tuple[str, int, int]],
    band_assignment: dict[int, str],
) -> dict[str, dict[str, int]]:
    """Query existing WordId→note_id for each target deck separately.

    Returns {deck_name: {WordId: note_id}}.
    Only queries decks that have at least one word assigned.
    """
    target_decks: set[str] = set(band_assignment.values())
    result: dict[str, dict[str, int]] = {}
    for deck in target_decks:
        result[deck] = ac.get_word_id_map(deck)
    return result


# _cmu_ipa() imported from .ipa


def _make_word_id(word_data: dict, book_id: str,
                   resolved_lemma: str | None = None) -> str:
    """Compute the canonical WordId for a word entry.

    WordId = {safe_filename(resolved_lemma)}_{book_id}

    This is the single source of truth for WordId construction, used by
    both the dedup check and build_note_entry.  Using the resolved lemma
    (not the surface form) ensures cross-book dedup consistency: variants
    like "pondered" and "pondering" from different books all map to the
    same lemma "ponder", preventing duplicate cards for the same root word.

    When *resolved_lemma* is provided (by the caller who already resolved
    it), it is used directly.  Otherwise, resolve_lemma() is called on
    the word_data to compute it — used by the dedup check where the lemma
    hasn't been resolved yet.
    """
    if resolved_lemma:
        resolved = resolved_lemma
    else:
        resolved = lemmatize(
            word_data["word"],
            json_lemma=word_data.get("lemma", ""),
        )
    return f"{safe_filename(resolved)}_{book_id}"


def _has_be_to_pattern(doc, vbn_idx: int) -> bool:
    """Check if the VBN at vbn_idx is part of a "be VBN to <verb>" pattern.

    "be astonished to see", "be surprised to hear" etc. — emotional
    adjectives with to-infinitive complement.  spaCy's small model often
    tags these as VERB/VBN rather than ADJ, but the structural pattern
    (form of "be" before, "to" + verb after) is a reliable adjective signal.
    """
    # Check preceding tokens: a form of "be" within 3 tokens before
    be_forms = {"am", "is", "are", "was", "were", "be", "been", "being"}
    has_be = False
    for i in range(max(0, vbn_idx - 3), vbn_idx):
        if doc[i].text.lower() in be_forms:
            has_be = True
            break
    if not has_be:
        return False

    # Check following tokens: "to" within 2 tokens after, followed by verb
    for i in range(vbn_idx + 1, min(vbn_idx + 3, len(doc))):
        if doc[i].text.lower() == "to" and i + 1 < len(doc):
            if doc[i + 1].pos_ == "VERB":
                return True
            # Also catch adverbs between "to" and verb: "to properly see"
            if i + 2 < len(doc) and doc[i + 2].pos_ == "VERB":
                return True
    return False


def _process_one_word(
    w: dict,
    book_id: str,
    no_audio: bool,
) -> tuple[dict, list[tuple[str, bytes]], str]:
    """Generate audio and build a note for a single word.

    Runs in a thread so it can be subject to a per-word timeout.

    Returns (note, audio_uploads, ipa).
    """
    word = w["word"]
    json_lemma = w.get("lemma", "").strip()
    lemma = lemmatize(word, json_lemma=json_lemma)

    # Safety net: for -ed/-ing words that resolve_lemma reduced away from
    # the surface form, verify with spaCy's sentence-context parse.
    #
    # Four signals that the surface form is a derivational adjective
    # (keep it) rather than a verb inflection (reduce to stem),
    # ordered by reliability — most confident first, broader heuristics later:
    #
    #   1. POS tag: spaCy directly tags the token as ADJ — most precise,
    #      near-zero false positives.  Fires first.
    #      — catches: blundering (JJ), interesting (JJ)
    #
    #   2. Dependency: the token has an adjectival grammatical function
    #      (acomp/oprd/attr/amod).  Broader than POS — catches adjectives
    #      spaCy tagged as VERB but parsed as adjectival modifiers.
    #      — catches: surprised (acomp), disappointed (oprd), distinguished (amod)
    #
    #   3. Lemma: spaCy returns the surface form as its own lemma — the
    #      lemmatizer itself refuses to reduce.  Belt & suspenders.
    #      — catches: embarrassed (lemma=embarrassed)
    #
    #   4. be-to pattern: "be VBN to <verb>" — emotional adjective with
    #      to-infinitive complement.  spaCy often misparses this as ROOT
    #      (passive) instead of acomp.
    #      — catches: astonished ("was astonished to see")
    wl = word.lower()
    if lemma != wl and wl.endswith(("ed", "ing")):
        sent = w.get("sentence", "")
        if sent:
            nlp = _get_spacy(enable_parser=True)
            if nlp is not None:
                try:
                    doc = nlp(sent)
                    for token in doc:
                        if token.text.lower() == wl:
                            # Signal 1: POS tag — most precise, fires first
                            if token.pos_ == "ADJ":
                                lemma = wl
                                break
                            # Signal 2: adjectival dependency relation
                            if token.dep_ in ("acomp", "oprd", "attr", "amod"):
                                lemma = wl
                                break
                            # Signal 3: spaCy lemma == surface form
                            if token.lemma_.lower() == wl:
                                lemma = wl
                                break
                            # Signal 4: be VBN to <verb> structural pattern
                            if token.tag_ == "VBN" and _has_be_to_pattern(doc, token.i):
                                lemma = wl
                                break
                except Exception:
                    pass

    safe = safe_filename(lemma)

    # IPA: cmudict preferred.  Claude's IPA used as tiebreaker for
    # heteronyms (read/read, wound/wound) and fallback for OOV words.
    cmu_ipa = _cmu_ipa(lemma, w.get("ipa", ""))
    ipa = cmu_ipa if cmu_ipa else w.get("ipa", "")

    audio_uploads: list[tuple[str, bytes]] = []

    if not no_audio:
        # Word audio: Edge TTS on lemma (with IPA if available).
        #   Include book_id — heteronyms like "wound" have different
        #   pronunciations in different books.
        if ipa:
            tts = edge_tts_bytes(lemma, ipa=ipa)
            if tts:
                audio_uploads.append((f"{safe}_{book_id}_word.mp3", tts))
            else:
                raise RuntimeError(
                    f"Word audio generation failed for '{lemma}' "
                    f"(TTS returned no data after {EDGE_TTS_MAX_RETRIES + 1} attempts)"
                )

        # Sentence audio: Edge TTS on cleaned sentence.
        #   Include book_id in filename — different books have different
        #   sentences for the same lemma (e.g. "beautiful" in two books).
        clean = re.sub(r"<[^>]+>", "", w["sentence"])
        sent_tts = edge_tts_bytes(clean)
        if sent_tts:
            audio_uploads.append((f"{safe}_{book_id}_sent.mp3", sent_tts))
        else:
            raise RuntimeError(
                f"Sentence audio generation failed for '{word}' "
                f"(TTS returned no data after {EDGE_TTS_MAX_RETRIES + 1} attempts)"
            )

    note = build_note_entry(w, ipa, book_id, lemma=lemma)
    # Preserve original index in new_words for correct band assignment.
    orig_idx = w.get("_idx")
    if orig_idx is not None:
        note["_idx"] = orig_idx
    return note, audio_uploads, ipa


def build_note_entry(
    word_data: dict,
    ipa: str | None,
    book_id: str,
    lemma: str | None = None,
) -> dict:
    """Build a single AnkiConnect note dict from word data.

    Audio files are referenced as [sound:filename.mp3] — the actual
    media files must be uploaded separately via store_media_file().

    If lemma is provided, it's used for the card Word field, audio
    filenames, and WordId.  WordId uses the resolved lemma for
    cross-book dedup consistency (see _make_word_id).
    """
    # WordId uses the resolved lemma — variants like "pondered" and
    # "pondering" map to the same WordId "ponder_{book_id}".
    # Use _make_word_id (single source of truth) so build_note_entry
    # and the dedup check always compute the same WordId.
    surface = word_data["word"].strip().lower()
    safe_lemma = safe_filename(lemma) if lemma else safe_filename(surface)
    word_id = _make_word_id(word_data, book_id, resolved_lemma=lemma)
    word_audio_ref = f"[sound:{safe_lemma}_{book_id}_word.mp3]"
    sent_audio_ref = f"[sound:{safe_lemma}_{book_id}_sent.mp3]"

    return {
        "deckName": "",  # filled in later by caller
        "modelName": MODEL_NAME,
        "fields": {
            "WordId": word_id,
            "Word": lemma if lemma else surface,
            "Sentence": word_data["sentence"],
            "IPA": ipa or word_data.get("ipa", ""),
            "DefinitionCN": word_data["definition_cn"],
            "TranslationCN": word_data["translation_cn"],
            "WordAudio": word_audio_ref,
            "SentenceAudio": sent_audio_ref,
        },
        "tags": ["weread"],
    }


# _validate_word_entries() imported from .validation
# _find_anki_media_dir(), _upload_media_direct(), _repair_audio() imported from .audio

def _dummy_removed() -> None:  # placeholder — real code moved to validation.py + audio.py
    pass


# _validate_word_entries() imported from .validation
# _find_anki_media_dir(), _upload_media_direct(), _repair_audio() imported from .audio

def sync(
    data: dict,
    deck_name: str,
    dry_run: bool = False,
    no_audio: bool = False,
    verbose: bool = False,
    word_timeout: int = WORD_TIMEOUT,
    prefetch: bool = False,
    audio_dir: str | None = None,
    no_direct_media: bool = False,
    no_ankiweb_sync: bool = False,
    max_bands: int = 5,
    min_band_size: int = 100,
) -> dict:
    """Run the full sync workflow. Returns a summary dict."""
    words = data["words"]
    book_title = data["book_title"]

    book_id = data.get("book_id", "")

    # 1. Connect to Anki (skip for prefetch — audio-only mode)
    ac = None

    # Compute frequency bands from the full word list (before dedup).
    # band_assignment maps word_index in new_words → deck_name;
    # populated after new_words is finalized below.
    band_assignment: dict[int, str] = {}
    bands = compute_bands(
        _count_coca_levels(words), max_bands, min_band_size
    )

    # Format band names with book prefix for share-friendly naming.
    # e.g. "COCA 4" → "Book Title (Author) - COCA 4"
    if bands:
        author = data.get("book_author", "")
        book_prefix = f"{book_title} ({author})" if author else book_title
        bands = [(f"{book_prefix} - {name}", lo, hi) for name, lo, hi in bands]

    if not prefetch:
        print(f'Connecting to AnkiConnect...')
        ac = AnkiConnect()

        # 2. Create hierarchical decks (or flat deck if no bands)
        if bands:
            # Create parent deck first
            ac.ensure_deck_and_model(deck_name, MODEL_NAME)
            print(f'  Deck: "{deck_name}" (parent)')

            # Create each band sub-deck
            for band_name, _lo, _hi in bands:
                sub_deck = f"{deck_name}::{band_name}"
                ac.ensure_deck_and_model(sub_deck, MODEL_NAME)
                print(f'    └ "{band_name}"')

            # Pre-compute band assignment for all input words.
            # Each word is only deduped against its own target sub-deck.
            _pre_assign_bands(words, deck_name, bands, band_assignment)
            print(f"\nQuerying existing cards per sub-deck...")
            existing = _get_existing_per_deck(ac, deck_name, bands, band_assignment)
            total_existing = sum(len(v) for v in existing.values())
            print(f"  Found {total_existing} existing cards across {len(existing)} decks")
        else:
            # Single flat deck
            ac.ensure_deck_and_model(deck_name, MODEL_NAME)
            print(f'  Deck: "{deck_name}"')
            print(f"  Model: {MODEL_NAME}")

            # Get existing WordId map from target deck
            print(f"\nQuerying existing cards in deck...")
            existing = {"": ac.get_word_id_map(deck_name)}
            print(f"  Found {len(existing[''])} existing cards")
    else:
        existing = {}  # prefetch: no Anki connection, skip dedup

    # 5. Identify new words (WordId = safe_filename(resolved_lemma)_book_id).
    new_words = []
    skipped_words = []
    for idx, w in enumerate(words):
        original_id = _make_word_id(w, book_id)

        # Only dedup against this word's target deck
        target_deck = band_assignment.get(idx, deck_name)
        deck_cards = existing.get(target_deck, {})
        if original_id in deck_cards:
            if verbose:
                print(f"  SKIP {w['word']} (already in deck)")
            skipped_words.append(w)
        else:
            new_words.append(w)



    # Rebuild band_assignment for new_words (0-based indices after dedup)
    if bands:
        band_assignment.clear()
        band_map: dict[tuple[int, int], str] = {}
        for band_name, lo, hi in bands:
            band_map[(lo, hi)] = f"{deck_name}::{band_name}"
        for idx, w in enumerate(new_words):
            lvl = w.get("coca_level")
            if isinstance(lvl, int):
                for (lo, hi), sub_deck in band_map.items():
                    if lo <= lvl <= hi:
                        band_assignment[idx] = sub_deck
                        break
            if idx not in band_assignment:
                band_assignment[idx] = deck_name
        # Print band distribution
        band_counts: dict[str, int] = {}
        for deck in band_assignment.values():
            short = deck.split("::")[-1] if "::" in deck else deck
            band_counts[short] = band_counts.get(short, 0) + 1
        print(f"\n  Band distribution: {', '.join(f'{k}: {v}' for k, v in band_counts.items())}")

    print(f"\n  New words to add: {len(new_words)}")
    print(f"  Already in deck: {len(skipped_words)}")

    if not new_words:
        print("\nDeck is up to date — nothing to add.")
        return {
            "added": 0,
            "skipped": len(skipped_words),
            "audio_uploaded": 0,
            "words_added": [],
            "words_skipped": [w["word"] for w in skipped_words],
        }

    if dry_run:
        print(f"\n[DRY RUN] Would add:")
        for w in new_words:
            print(f"  + {w['word']}")
        return {
            "added": len(new_words),
            "skipped": len(skipped_words),
            "audio_uploaded": 0,
            "words_added": [w["word"] for w in new_words],
            "words_skipped": [w["word"] for w in skipped_words],
        }

    # 6. Generate audio and build notes for new words (parallel)
    if prefetch:
        print(f"\nPrefetching audio for {len(new_words)} new words (parallel)...")
    else:
        print(f"\nGenerating audio for {len(new_words)} new words (parallel)...")
    notes_to_add = []
    audio_uploads: list[tuple[str, bytes]] = []
    failed_words: list[str] = []
    word_ok = 0
    sent_ok = 0
    total = len(new_words)

    if audio_dir:
        # Load pre-generated audio from disk and build notes
        manifest_path = os.path.join(audio_dir, "manifest.json")
        if not os.path.isfile(manifest_path):
            print(f"Error: manifest not found at {manifest_path}", file=sys.stderr)
            sys.exit(1)
        with open(manifest_path, "r", encoding="utf-8") as mf:
            manifest = json.load(mf)
        # Restore notes (without deckName — fill in below).
        # Use _idx (original position in new_words) for correct band
        # assignment, because manifest notes are in completion order
        # (ThreadPoolExecutor) not submission order.
        for i, note in enumerate(manifest["notes"]):
            orig_idx = note.get("_idx", i)  # fallback: old manifests lack _idx
            note["deckName"] = band_assignment.get(orig_idx, deck_name)
            notes_to_add.append(note)
        # Load audio files from disk
        for filename, filepath in manifest["audio_files"].items():
            if os.path.isfile(filepath):
                with open(filepath, "rb") as af:
                    audio_uploads.append((filename, af.read()))
        word_ok = manifest["stats"]["word_ok"]
        sent_ok = manifest["stats"]["sent_ok"]
        print(f"  Loaded {len(notes_to_add)} notes + {len(audio_uploads)} audio files from cache")
    else:
        # Generate audio concurrently
        max_workers = min(16, len(new_words))
        if verbose:
            print(f"  ({max_workers} workers)")

        # Inject _idx before thread pool so each note preserves its
        # original position for correct band assignment.
        for idx, w in enumerate(new_words):
            w["_idx"] = idx

        with concurrent.futures.ThreadPoolExecutor(max_workers=max_workers) as executor:
            future_map = {
                executor.submit(_process_one_word, w, book_id, no_audio): (idx, w)
                for idx, w in enumerate(new_words)
            }

            completed = 0
            for future in concurrent.futures.as_completed(future_map):
                idx, w = future_map[future]
                word = w["word"]
                lemma = lemmatize_word(word)
                completed += 1

                try:
                    note, word_audio, final_ipa = future.result()
                    note["deckName"] = band_assignment.get(idx, deck_name)
                    notes_to_add.append(note)
                    audio_uploads.extend(word_audio)

                    has_word = any(fn.endswith("_word.mp3") for fn, _ in word_audio)
                    has_sent = any(fn.endswith("_sent.mp3") for fn, _ in word_audio)
                    if has_word:
                        word_ok += 1
                    if has_sent:
                        sent_ok += 1

                    tag = f" ({lemma})" if lemma != word.lower() else ""
                    label = f"{word}{tag}"
                    if verbose and not no_audio:
                        parts = []
                        parts.append("word✓" if has_word else "word✗")
                        parts.append("sent✓" if has_sent else "sent✗")
                        label = f"{label}  audio: {', '.join(parts)}"
                    print_progress(completed, total, label)
                except Exception as e:
                    failed_words.append(word)
                    print()
                    print(f"  ✗ {word}: {e}")
                    print_progress(completed, total, word)

        print()

        # Mechanical check: verify every note's WordId matches _make_word_id.
        # This catches drift between build_note_entry and the dedup check —
        # both must use the same resolved-lemma WordId format.
        for note in notes_to_add:
            wid = note["fields"]["WordId"]
            # Reconstruct expected WordId from the same input that
            # build_note_entry received.  We don't have the original
            # word_data here, so validate by checking the WordId uses
            # the safe_filename(Word) pattern (Word field = resolve_lemma result).
            card_word = note["fields"]["Word"]
            expected_prefix = safe_filename(card_word)
            if not wid.startswith(expected_prefix + "_"):
                raise AssertionError(
                    f"WordId mismatch: note WordId={wid!r} but card Word={card_word!r} "
                    f"(expected WordId to start with {expected_prefix!r}_)"
                )

        # If prefetch mode: save to temp dir with manifest, then exit
        if prefetch:
            prefetch_dir = tempfile.mkdtemp(prefix="vocab_audio_")
            audio_files: dict[str, str] = {}

            for filename, data in audio_uploads:
                filepath = os.path.join(prefetch_dir, filename)
                with open(filepath, "wb") as af:
                    af.write(data)
                audio_files[filename] = filepath

            # Strip deckName from notes (will be filled in at sync time)
            saved_notes = []
            for note in notes_to_add:
                saved = dict(note)
                saved.pop("deckName", None)
                saved_notes.append(saved)

            manifest = {
                "notes": saved_notes,
                "audio_files": audio_files,
                "stats": {
                    "total": total,
                    "word_ok": word_ok,
                    "sent_ok": sent_ok,
                    "failed": len(failed_words),
                },
                "failed_words": failed_words,
            }
            manifest_path = os.path.join(prefetch_dir, "manifest.json")
            with open(manifest_path, "w", encoding="utf-8") as mf:
                json.dump(manifest, mf, indent=2, ensure_ascii=False)

            print(f"\nAudio prefetch complete:")
            print(f"  Word audio:  {word_ok}/{total}")
            print(f"  Sentence:    {sent_ok}/{total}")
            if failed_words:
                raise RuntimeError(
                    f"Audio generation failed for {len(failed_words)} word(s) "
                    f"after {EDGE_TTS_MAX_RETRIES + 1} attempts each: "
                    f"{', '.join(failed_words)}"
                )
            print(f"\nAUDIO_DIR={prefetch_dir}")
            return {
                "added": 0,
                "skipped": len(skipped_words),
                "audio_uploaded": len(audio_uploads),
                "words_added": [],
                "words_skipped": [w["word"] for w in skipped_words],
                "failed_words": failed_words,
                "prefetch_dir": prefetch_dir,
                "prefetch_stats": manifest["stats"],
            }

    # 7. Upload media files (direct filesystem copy, fallback to AnkiConnect)
    audio_count = 0
    if audio_uploads and not dry_run:
        total_media = len(audio_uploads)
        media_dir = None if no_direct_media else _find_anki_media_dir()

        if media_dir:
            # Fast path: copy files directly into collection.media (~0.7s for 124 files)
            print(f"\nCopying {total_media} media files to Anki media dir...")
            if verbose:
                print(f"  {media_dir}")
            audio_count = _upload_media_direct(audio_uploads, media_dir, verbose=verbose)
            print()
            print(f"  Copied: {audio_count}/{total_media}")
        else:
            # Slow path: upload through AnkiConnect (per-file base64 + SQLite overhead)
            batch_size = 40
            print(f"\nUploading {total_media} media files via AnkiConnect (batched ×{batch_size})...")
            for batch_start in range(0, total_media, batch_size):
                batch = audio_uploads[batch_start:batch_start + batch_size]
                try:
                    results = ac.store_media_files_batch(batch, batch_size=batch_size)
                    for i, result in enumerate(results):
                        filename, audio_data = batch[i]
                        global_idx = batch_start + i + 1
                        if result is not None:
                            audio_count += 1
                            if verbose:
                                print_progress(global_idx, total_media, f"{filename} ({len(audio_data)} bytes)")
                            else:
                                print_progress(global_idx, total_media)
                        else:
                            print()
                            print(f"  ✗ {filename}: failed (duplicate or error)")
                            print_progress(global_idx, total_media)
                except AnkiConnectError as e:
                    for i, (filename, _data) in enumerate(batch):
                        global_idx = batch_start + i + 1
                        print()
                        print(f"  ✗ {filename}: {e}")
                        print_progress(global_idx, total_media)
            print()
            print(f"  Uploaded: {audio_count}/{total_media}")

    # 8. Add notes
    added_count = 0
    duped_count = 0
    if not dry_run and notes_to_add:
        print(f"\nAdding {len(notes_to_add)} new cards to Anki...")
        try:
            # Strip internal _idx before sending to AnkiConnect
            for note in notes_to_add:
                note.pop("_idx", None)
            result = ac.add_notes(notes_to_add)
            added_count = sum(1 for r in result if r is not None)
            duped_count = sum(1 for r in result if r is None)
            print(f"  Added: {added_count}")
            if duped_count:
                print(f"  Duplicates (not added): {duped_count}")
        except AnkiConnectError as e:
            errmsg = str(e)
            if "duplicate" in errmsg.lower():
                print(f"  All {len(notes_to_add)} already exist (duplicates).")
                duped_count = len(notes_to_add)
            else:
                print(f"Error adding notes: {e}")
                return {
                    "added": 0,
                    "skipped": len(skipped_words),
                    "audio_uploaded": audio_count,
                    "words_added": [],
                    "words_skipped": [w["word"] for w in skipped_words + new_words],
                    "failed_words": failed_words,
                    "error": errmsg,
                }

    # 9. Trigger AnkiWeb sync (fire-and-forget)
    ankiweb_synced = False
    if ac and not no_ankiweb_sync and not dry_run:
        try:
            ac.sync()
            ankiweb_synced = True
            print(f"\nAnkiWeb sync triggered.")
        except AnkiConnectError as e:
            print(f"\nAnkiWeb sync skipped: {e}")

    # Summary
    print(f"\n{'='*50}")
    print(f"Sync complete for \"{book_title}\"")
    print(f"  New cards added:  {added_count}")
    print(f"  Already in deck:  {len(skipped_words)}")
    print(f"  Media uploaded:   {audio_count}")
    if data.get("excluded"):
        print(f"  Excluded (COCA):  {len(data.get('excluded', []))} word(s)")
    if failed_words:
        raise RuntimeError(
            f"Audio generation failed for {len(failed_words)} word(s) "
            f"after {EDGE_TTS_MAX_RETRIES + 1} attempts each: "
            f"{', '.join(failed_words)}"
        )
    print(f"{'='*50}")

    return {
        "added": added_count,
        "skipped": len(skipped_words),
        "audio_uploaded": audio_count,
        "words_added": [w["word"] for w in new_words[:added_count]],
        "words_skipped": [w["word"] for w in skipped_words],
        "failed_words": failed_words,
        "ankiweb_synced": ankiweb_synced,
    }


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------


def main() -> None:
    args = parse_args()

    # Read input
    with open(args.input_file, "r", encoding="utf-8") as f:
        data = json.load(f)

    # Basic validation
    if not data.get("book_title"):
        print("Error: missing 'book_title' in input", file=sys.stderr)
        sys.exit(1)
    if not data.get("book_id"):
        print("Error: missing 'book_id' in input", file=sys.stderr)
        sys.exit(1)
    if not data.get("words"):
        print("Error: 'words' array is empty", file=sys.stderr)
        sys.exit(1)

    # Deduplicate
    seen = set()
    deduped = []
    for w in data["words"]:
        key = w["word"].strip().lower()
        if key not in seen:
            seen.add(key)
            deduped.append(w)
    if len(deduped) < len(data["words"]):
        print(f"Note: deduplicated {len(data['words']) - len(deduped)} word(s)\n")
    data["words"] = deduped

    # Pre-fill IPA from cmudict before validation.
    # Claude may leave ipa empty — cmudict fills it automatically for known words.
    # Only words truly not in cmudict will still have empty ipa and fail validation
    # (requiring Claude to provide a manual IPA).
    for w in data["words"]:
        if not w.get("ipa", "").strip():
            json_lemma = w.get("lemma", "").strip()
            lookup_word = json_lemma if json_lemma else w["word"]
            cmu_ipa = _cmu_ipa(lookup_word)
            if cmu_ipa:
                w["ipa"] = cmu_ipa

    # Validate quality rules before sync
    errors = validate_word_entries(data["words"])
    if errors:
        print(f"Quality check FAILED ({len(errors)} error(s)):", file=sys.stderr)
        for e in errors:
            print(f"  {e}", file=sys.stderr)
        sys.exit(1)

    # Deck name resolution priority:
    #   1. JSON deck_name field (set by Claude from Step 0b {deck: bookId} mapping)
    #   2. --deck CLI flag (explicit override)
    #   3. Auto-derive from book_title + book_author (new deck, fallback)
    json_deck = data.get("deck_name", "").strip()
    if json_deck:
        deck_name = json_deck
    elif args.deck:
        deck_name = args.deck
    else:
        author = data.get("book_author", "")
        title = data["book_title"]
        deck_name = f"{title} ({author})" if author else f"{title} Vocabulary"

    try:
        result = sync(
            data,
            deck_name,
            dry_run=args.dry_run,
            no_audio=args.no_audio,
            verbose=args.verbose,
            word_timeout=args.word_timeout,
            prefetch=args.prefetch,
            audio_dir=args.audio_dir,
            no_direct_media=args.no_direct_media,
            no_ankiweb_sync=args.no_ankiweb_sync,
            max_bands=args.max_bands,
            min_band_size=args.min_band_size,
        )
        if result.get("error"):
            sys.exit(1)
    except AnkiConnectError as e:
        print(f"\nError: {e}", file=sys.stderr)
        print(
            "\nMake sure:\n"
            "  1. Anki is running\n"
            '  2. AnkiConnect plugin is installed (add-on code: 2055492159)\n'
            "  3. The Vocabulary Card (WeRead) model exists in Anki\n"
            "     (import an .apkg file from this skill first)",
            file=sys.stderr,
        )
        sys.exit(1)


# ---------------------------------------------------------------------------
# ARPAbet → IPA conversion gold-standard tests
# ---------------------------------------------------------------------------


def _test_arpabet_to_ipa() -> None:
    """Verify ARPAbet→IPA mapping against known-correct gold standards.

    Never remove or weaken a test case — the mapping is the single source
    of truth for all card IPA generation.
    """
    failures = 0

    def check(word: str, expected: str) -> None:
        nonlocal failures
        got = _cmu_ipa(word)  # no Claude IPA → uses first entry
        if got != expected:
            failures += 1
            print(f"  FAIL: {word} → {got} (expected {expected})", file=sys.stderr)

    # ── Vowel length distinctions (tense vs lax) ──
    #   Monosyllabic: no stress mark (standard IPA convention)
    check("feed", "/fiːd/")          # IY → iː
    check("fed", "/fed/")            # EH → e
    check("fit", "/fɪt/")            # IH → ɪ
    check("food", "/fuːd/")          # UW → uː
    check("foot", "/fʊt/")           # UH → ʊ
    check("fast", "/fæst/")          # AE → æ
    check("father", "/ˈfɑːðər/")     # AA → ɑː, ER0 → ər
    check("law", "/lɔː/")            # AO → ɔː, unambiguous in cmudict
    check("cup", "/kʌp/")            # AH → ʌ
    check("bird", "/bɜːrd/")         # ER1 → ɜːr (monosyllabic, no stress)

    # ── Diphthongs ──
    check("day", "/deɪ/")            # EY → eɪ
    check("go", "/ɡoʊ/")             # OW → oʊ
    check("my", "/maɪ/")             # AY → aɪ
    check("now", "/naʊ/")            # AW → aʊ
    check("boy", "/bɔɪ/")            # OY → ɔɪ

    # ── Consonants ──
    check("thin", "/θɪn/")           # TH → θ
    check("this", "/ðɪs/")           # DH → ð
    check("ship", "/ʃɪp/")           # SH → ʃ
    check("chip", "/tʃɪp/")          # CH → tʃ
    check("judge", "/dʒʌdʒ/")        # JH → dʒ
    check("sing", "/sɪŋ/")           # NG → ŋ
    check("measure", "/ˈmeʒər/")     # ZH → ʒ, ER0 → ər
    check("yes", "/jes/")            # Y → j

    # ── Multi-syllable stress ──
    check("hunting", "/ˈhʌntɪŋ/")
    check("accomplished", "/əˈkɑːmplɪʃt/")
    check("distinguished", "/dɪˈstɪŋɡwɪʃt/")
    check("beautiful", "/ˈbjuːtəfəl/")
    check("blundering", "/ˈblʌndərɪŋ/")
    check("comfortable", "/ˈkʌmfərtəbəl/")

    if failures:
        print(f"\n  {failures} ARPAbet→IPA test(s) FAILED", file=sys.stderr)
        sys.exit(1)
    else:
        print(f"  ARPAbet→IPA: all {29} tests passed ✓")


if __name__ == "__main__":
    main()
